#!/usr/bin/env python
"""
Created on Oct 27, 2014

@author: Maria
"""

# -*- coding: utf-8 -*-


linker1 = ['ACTGGCCTGCGA']
linker2 = ['GGTAGCGGTGAC']

cell_key1 = [
                 "TTAACGCG",
                 "TGTGCTGA",
                 "TCGAGTTG",
                 "TTGGCGAT",
                 "GCATCCAA",
                 "TATACGCG",
                 "GAGTTCTG",
                 "ATGCTTGG",
                 "TCCTCAAC",
                 "CCTAATCC",
                 "CGAACGTT",
                 "TTGCCGTT",
                 "AGCTCAAC",
                 "ATCCGGTA",
                 "AAGCAAGC",
                 "CACTCAGA",
                 "CAAGGTTC",
                 "AGGATGGT",
                 "TAGGATGG",
                 "ACACACAC",
                 "CACATCTC",
                 "TCCACTTG",
                 "TCCATGCT",
                 "GCAAGGAT",
                 "GGATATGG",
                 "TTGCATCC",
                 "CAGACACT",
                 "GGATAACG",
                 "CTAGTGGT",
                 "TGTGACTG",
                 "TATAGCCG",
                 "TCTGGTCT",
                 "ATGGATGG",
                 "GCAAGGTA",
                 "TGGATGCT",
                 "CAACTCGA",
                 "GCATGCAT",
                 "TCCTTGGT",
                 "AAGCAACG",
                 "AACGCGAA",
                 "TCTCTGTG",
                 "AATACGCC",
                 "AACGATGG",
                 "TCGACAAC",
                 "TAGCCGAT",
                 "TGCACTTC",
                 "GATCCATG",
                 "TGGTTGGT",
                 "CAACGTAC",
                 "ATTAGCCG",
                 "TCCAACCT",
                 "CTTGGATG",
                 "ACGAACCT",
                 "CCATTAGG",
                 "GCAAGCTT",
                 "ACAGCACT",
                 "AGTCTCTC",
                 "AGTGAGTG",
                 "TTCCATGC",
                 "CCATAACG",
                 "TGGACTTG",
                 "TTAAGCCG",
                 "TCGACTTC",
                 "GCATGGTT",
                 "CTTCCAAC",
                 "CAACCATG",
                 "TCCTAGCT",
                 "GTGACACT",
                 "GCAATAGG",
                 "TGACACAC",
                 "TTGCCGAA",
                 "TTCCAAGG",
                 "AACCTAGC",
                 "AAGCCGTT",
                 "AACGCCTA",
                 "TTAACGGC",
                 "ATCCTTGC",
                 "GGTACGAA",
                 "AACGGCTT",
                 "CACTGAGT",
                 "GGTTCCTT",
                 "CTTCTCCT",
                 "CTAGGTTG",
                 "AAGGATGC",
                 "TCAGACTG",
                 "TGTGGACT",
                 "TTCCTTGG",
                 "TAGGTTCG",
                 "AGCTTGGT",
                 "ATTACGCG",
                 "AACCATGC",
                 "TGCAACGT",
                 "AGGTGAAC",
                 "TGTCTGTC",
                 "GATCTGGT",
                 "CTGACTGA",
                 "ATCGGCAT"
                 ]
# combinatorial_bc2
cell_key2 = ["TGGTCTTC",
                 "CAACAGCT",
                 "GGTACGTT",
                 "TGGAGTTC",
                 "TTGCAAGC",
                 "TTATGGCG",
                 "CAACACGT",
                 "CCAACCAA",
                 "TCTCTGAC",
                 "CTTGTGCT",
                 "AGCTTCCT",
                 "AGTCCTCT",
                 "GAACCATC",
                 "CTTGACGA",
                 "CATCCTTG",
                 "CCTATTGC",
                 "TGGTTCCT",
                 "TGCATGGT",
                 "CCTAGCTT",
                 "GCATAAGG",
                 "CACATGAC",
                 "CCAATTCC",
                 "AAGCCGAA",
                 "ACTCAGAC",
                 "GCAATTCG",
                 "GATCTCCT",
                 "GACTCTGA",
                 "AGCAACGA",
                 "ACTGACTG",
                 "GCCGTTAA",
                 "CAACCAAC",
                 "AAGCTTGC",
                 "CAAGTGCT",
                 "GATGACCT",
                 "ACCTGATG",
                 "GTCTGTGA",
                 "CAACCTTC",
                 "AGGTACGA",
                 "ATCCAAGC",
                 "AGCTCATG",
                 "GTTCTGCT",
                 "TGCTTGCT",
                 "ACTGCTCT",
                 "ATGCCGTA",
                 "CCATATCC",
                 "AGTGGTCT",
                 "TGAGTCTG",
                 "CGATATGC",
                 "CGATTAGC",
                 "GATGACGA",
                 "TTCGATGG",
                 "GTTGCTTC",
                 "CTGAACTG",
                 "TAGCCGTA",
                 "ACCACAAC",
                 "GAACGATG",
                 "TGCTGTTC",
                 "AATTGCCG",
                 "TGTGCTCT",
                 "GGATGGAT",
                 "GATGGATG",
                 "GATGGTTC",
                 "ACGATGCT",
                 "CAAGGATG",
                 "GCAACGTT",
                 "TGCTCTTG",
                 "ATTACGGC",
                 "TGCTGATG",
                 "CTCAACTC",
                 "TGCACATG",
                 "CTTGGTTC",
                 "ACTGGACT",
                 "CTCTTCTC",
                 "TGGTTCGA",
                 "GTTCCATC",
                 "GGTTGCAT",
                 "TGGTACGT",
                 "GCGGTATT",
                 "GTTGTCCT",
                 "TTGCTTCG",
                 "ACACGACT",
                 "CATGGTAC",
                 "TCCTCATG",
                 "GGATGCAA",
                 "TTGCATGG",
                 "GATCCAAC",
                 "GATCAGCT",
                 "TGACCTGA",
                 "TGCATCCT",
                 "CGAATAGG",
                 "ATCCATCC",
                 "CTTCCTTC",
                 "AGGTCTTG",
                 "TGACTGAC",
                 "GGTTCGAT",
                 "GTTGCATG",
                 "CTTGCATC"
                 ]
# combinatorial_bc3
cell_key3 = ["CTGACTCT",
                 "GACTGACT",
                 "TAGCTTGG",
                 "CATGGTTG",
                 "CCATAAGC",
                 "TTCGAACG",
                 "CTCTCTGA",
                 "ACACTGTG",
                 "ATATGCCG",
                 "AACGGCAA",
                 "GCGGTTAT",
                 "ACTGTCTC",
                 "TGTCCACT",
                 "GAACTGCT",
                 "TCAGACAC",
                 "ACACACTG",
                 "ATAACGCC",
                 "GGTATTGC",
                 "CCAATACG",
                 "TCTCTCTC",
                 "TCTGACTC",
                 "AAGGTACG",
                 "GATGTGCT",
                 "GCCGTATA",
                 "TCTGTCTG",
                 "GTCTTCTG",
                 "TCGACATG",
                 "TCCTTCCT",
                 "CGATAAGG",
                 "TTGCAACG",
                 "GGTTCCAA",
                 "TGAGGAGT",
                 "GCATCCTT",
                 "CATCTGCT",
                 "CACACTCT",
                 "GATGAGGT",
                 "CGAACCAT",
                 "ACTGACAC",
                 "ACTCCACT",
                 "GCCGTAAT",
                 "TGAGGTCT",
                 "GTCTTGTC",
                 "AAGCATCC",
                 "CTGTTCTG",
                 "TCGAGTAC",
                 "CCTAATGG",
                 "CATGTCCT",
                 "GATGCTTG",
                 "GTGAGTCT",
                 "GCCGATAT",
                 "TCAGCTCT",
                 "GACTCTCT",
                 "CGAACGAA",
                 "TGCAAGCT",
                 "CAGAACTC",
                 "TCTGAGTG",
                 "ATGCATGC",
                 "AGTGGAGT",
                 "TGACCTCT",
                 "AGGAGTAC",
                 "TAGCTTCC",
                 "CTAGCAAC",
                 "GGTATTCG",
                 "CCTTCGAT",
                 "CTTCAGCT",
                 "TTCCGGTT",
                 "TCCAAGGT",
                 "GACATCTG",
                 "GGTTAAGG",
                 "GGATGGTA",
                 "TCCTGTTG",
                 "ACCTGAAC",
                 "ACTGAGTC",
                 "GTCTAGTG",
                 "ATGCGGTT",
                 "AACCAAGG",
                 "AGGACATG",
                 "AAGGTTGG",
                 "GCATTACG",
                 "TTGGTTGG",
                 "CGAATTGC",
                 "ACGACATC",
                 "CCAATAGC",
                 "ATGGTTGC",
                 "CTAGTCCT",
                 "TGACTCTC",
                 "GCAACCAT",
                 "AGGAGTTG",
                 "TCTGGTGA",
                 "AGCTGTTG",
                 "CTTGCTTG",
                 "CTCAAGTG",
                 "ATGCAAGG",
                 "CTAGGTAC",
                 "CCATGGTA",
                 "TATTGGCG",
                 "GAGTTGTC"
                 ]

v2_cell_key1 = ["GTCGCTATA",
                "CTTGTACTA",
                "CTTCACATA",
                "ACACGCCGG",
                "CGGTCCAGG",
                "AATCGAATG",
                "CCTAGTATA",
                "ATTGGCTAA",
                "AAGACATGC",
                "AAGGCGATC",
                "GTGTCCTTA",
                "GGATTAGGA",
                "ATGGATCCA",
                "ACATAAGCG",
                "AACTGTATT",
                "ACCTTGCGG",
                "CAGGTGTAG",
                "AGGAGATTA",
                "GCGATTACA",
                "ACCGGATAG",
                "CCACTTGGA",
                "AGAGAAGTT",
                "TAAGTTCGA",
                "ACGGATATT",
                "TGGCTCAGA",
                "GAATCTGTA",
                "ACCAAGGAC",
                "AGTATCTGT",
                "CACACACTA",
                "ATTAAGTGC",
                "AAGTAACCC",
                "AAATCCTGT",
                "CACATTGCA",
                "GCACTGTCA",
                "ATACTTAGG",
                "GCAATCCGA",
                "ACGCAATCA",
                "GAGTATTAG",
                "GACGGATTA",
                "CAGCTGACA",
                "CAACATATT",
                "AACTTCTCC",
                "CTATGAAAT",
                "ATTATTACC",
                "TACCGAGCA",
                "TCTCTTCAA",
                "TAAGCGTTA",
                "GCCTTACAA",
                "AGCACACAG",
                "ACAGTTCCG",
                "AGTAAAGCC",
                "CAGTTTCAC",
                "CGTTACTAA",
                "TTGTTCCAA",
                "AGAAGCACT",
                "CAGCAAGAT",
                "CAAACCGCC",
                "CTAACTCGC",
                "AATATTGGG",
                "AGAACTTCC",
                "CAAAGGCAC",
                "AAGCTCAAC",
                "TCCAGTCGA",
                "AGCCATCAC",
                "AACGAGAAG",
                "CTACAGAAC",
                "AGAGCTATG",
                "GAGGATGGA",
                "TGTACCTTA",
                "ACACACAAA",
                "TCAGGAGGA",
                "GAGGTGCTA",
                "ACCCTGACC",
                "ACAAGGATC",
                "ATCCCGGAG",
                "TATGTGGCA",
                "GCTGCCAAT",
                "ATCAGAGCT",
                "TCGAAGTGA",
                "ATAGACGAG",
                "AGCCCAATC",
                "CAGAATCGT",
                "ATCTCCACA",
                "ACGAAAGGT",
                "TAGCTTGTA",
                "ACACGAGAT",
                "AACCGCCTC",
                "ATTTAGATG",
                "CAAGCAAGC",
                "CAAAGTGTG",
                "GGCAAGCAA",
                "GAGCCAATA",
                "ATGTAATGG",
                "CCTGAGCAA",
                "GAGTACATT",
                "TGCGATCTA",
                "ATCACGTTA"
                ]

v2_cell_key2 = ["TACAGGATA",
                "CACCAGGTA",
                "TGTGAAGAA",
                "GATTCATCA",
                "CACCCAAAG",
                "CACAAAGGC",
                "GTGTGTCGA",
                "CTAGGTCCT",
                "ACAGTGGTA",
                "TCGTTAGCA",
                "AGCGACACC",
                "AAGCTACTT",
                "TGTTCTCCA",
                "ACGCGAAGC",
                "CAGAAATCG",
                "ACCAAAATG",
                "AGTGTTGTC",
                "TAGGGATAC",
                "AGGGCTGGT",
                "TCATCCTAA",
                "AATCCTGAA",
                "ATCCTAGGA",
                "ACGACCACC",
                "TTCCATTGA",
                "TAGTCTTGA",
                "ACTGTTAGA",
                "ATTCATCGT",
                "ACTTCGAGC",
                "TTGCGTACA",
                "CAGTGCCCG",
                "GACACTTAA",
                "AGGAGGCGC",
                "GCCTGTTCA",
                "GTACATCTA",
                "AATCAGTTT",
                "ACGATGAAT",
                "TGACAGACA",
                "ATTAGGCAT",
                "GGAGTCTAA",
                "TAGAACACA",
                "AAATAAATA",
                "CCGACAAGA",
                "CACCTACCC",
                "AAGAGTAGA",
                "TCATTGAGA",
                "GACCTTAGA",
                "CAAGACCTA",
                "GGAATGATA",
                "AAACGTACC",
                "ACTATCCTC",
                "CCGTATCTA",
                "ACACATGTC",
                "TTGGTATGA",
                "GTGCAGTAA",
                "AGGATTCAA",
                "AGAATGGAG",
                "CTCTCTCAA",
                "GCTAACTCA",
                "ATCAACCGA",
                "ATGAGTTAC",
                "ACTTGATGA",
                "ACTTTAACT",
                "TTGGAGGTA",
                "GCCAATGTA",
                "ATCCAACCG",
                "GATGAACTG",
                "CCATGCACA",
                "TAGTGACTA",
                "AAACTGCGC",
                "ATTACCAAG",
                "CACTCGAGA",
                "AACTCATTG",
                "CTTGCTTCA",
                "ACCTGAGTC",
                "AGGTTCGCT",
                "AAGGACTAT",
                "CGTTCGGTA",
                "AGATAGTTC",
                "CAATTGATC",
                "GCATGGCTA",
                "ACCAGGTGT",
                "AGCTGCCGT",
                "TATAGCCCT",
                "AGAGGACCA",
                "ACAATATGG",
                "CAGCACTTC",
                "CACTTATGT",
                "AGTGAAAGG",
                "AACCCTCGG",
                "AGGCAGCTA",
                "AACCAAAGT",
                "GAGTGCGAA",
                "CGCTAAGCA",
                "AATTATAAC",
                "TACTAGTCA",
                "CAACAACGG",
                "CGATGTTTA"
                ]

v2_cell_key3 = ["AAGCCTTCT",
                "ATCATTCTG",
                "CACAAGTAT",
                "ACACCTTAG",
                "GAACGACAA",
                "AGTCTGTAC",
                "AAATTACAG",
                "GGCTACAGA",
                "AATGTATCG",
                "CAAGTAGAA",
                "GATCTCTTA",
                "AACAACGCG",
                "GGTGAGTTA",
                "CAGGGAGGG",
                "TCCGTCTTA",
                "TGCATAGTA",
                "ACTTACGAT",
                "TGTATGCGA",
                "GCTCCTTGA",
                "GGCACAACA",
                "CTCAAGACA",
                "ACGCTGTTG",
                "ATATTGTAA",
                "AAGTTTACG",
                "CAGCCTGGC",
                "CTATTAGCC",
                "CAAACGTGG",
                "AAAGTCATT",
                "GTCTTGGCA",
                "GATCAGCGA",
                "ACATTCGGC",
                "AGTAATTAG",
                "TGAAGCCAA",
                "TCTACGACA",
                "CATAACGTT",
                "ATGGGACTC",
                "GATAGAGGA",
                "CTACATGCG",
                "CAACGATCT",
                "GTTAGCCTA",
                "AGTTGCATC",
                "AAGGGAACT",
                "ACTACATAT",
                "CTAAGCTTC",
                "ACGAACCAG",
                "TACTTCGGA",
                "AACATCCAT",
                "AGCCTGGTT",
                "CAAGTTTCC",
                "CAGGCATTT",
                "ACGTGGGAG",
                "TCTCACGGA",
                "GCAACATTA",
                "ATGGTCCGT",
                "CTATCATGA",
                "CAATACAAG",
                "AAAGAGGCC",
                "GTAGAAGCA",
                "GCTATGGAA",
                "ACTCCAGGG",
                "ACAAGTGCA",
                "GATGGTCCA",
                "TCCTCAATA",
                "AATAAACAA",
                "CTGTACGGA",
                "CTAGATAGA",
                "AGCTATGTG",
                "AAATGGAGG",
                "AGCCGCAAG",
                "ACAGTAAAC",
                "AACGTGTGA",
                "ACTGAATTC",
                "AAGGGTCAG",
                "TGTCTATCA",
                "TCAGATTCA",
                "CACGATCCG",
                "AACAGAAAC",
                "CATGAATGA",
                "CGTACTACG",
                "TTCAGCTCA",
                "AAGGCCGCA",
                "GGTTGGACA",
                "CGTCTAGGT",
                "AATTCGGCG",
                "CAACCTCCA",
                "CAATAGGGT",
                "ACAGGCTCC",
                "ACAACTAGT",
                "AGTTGTTCT",
                "AATTACCGG",
                "ACAAACTTT",
                "TCTCGGTTA",
                "ACTAGACCG",
                "ACTCATACG",
                "ATCGAGTCT",
                "CATAGGTCA",
                "TTAGGCATA"
                ]


barcodes_96 = {"ACAGTGCT": "A01",
               "ACATGCGT": "A02",
               "ACCGATTG": "A03",
               "ACCTTGAG": "A04",
               "ACGATGTC": "A05",
               "ACGTATGC": "A06",
               "ACTCTGGA": "A07",
               "ACTGGCTA": "A08",
               "AGACCTTG": "A09",
               "AGATTCCG": "A10",
               "AGCCGACC": "A11",
               "AGCGCTGC": "A12",
               "AGCTAGTC": "B01",
               "AGGCTCTA": "B02",
               "AGGTCTCA": "B03",
               "AGTACTAT": "B04",
               "AGTCAGCT": "B05",
               "AGTGTCGT": "B06",
               "ATACGTGC": "B07",
               "ATAGCGTC": "B08",
               "ATCGGTCA": "B09",
               "ATCTCGGA": "B10",
               "ATGACGCT": "B11",
               "ATTCCGAG": "B12",
               "ATTGACCG": "C01",
               "CAGAGTTC": "C02",
               "CAGCCGAC": "C03",
               "CAGTTAGC": "C04",
               "CATCGTGA": "C05",
               "CATGCGTA": "C06",
               "CCAGTTAG": "C07",
               "CCATGGCG": "C08",
               "CCGATTGA": "C09",
               "CGACCAGC": "C10",
               "CGAGATTC": "C11",
               "CGATTGAC": "C12",
               "CGCATGTA": "D01",
               "CGCTATGA": "D02",
               "CGTACATG": "D03",
               "CGTCATAG": "D04",
               "CTACGACA": "D05",
               "CTAGCTGA": "D06",
               "CTATAGTA": "D07",
               "CTGACTAG": "D08",
               "CTGCAGCG": "D09",
               "CTGTGATG": "D10",
               "CTTAGAGC": "D11",
               "CTTGAGAC": "D12",
               "GACCAGCC": "E01",
               "GACGTCGC": "E02",
               "GACTGATC": "E03",
               "GAGCCTTA": "E04",
               "GAGTTCCA": "E05",
               "GATATCAT": "E06",
               "GATCGACT": "E07",
               "GATGCTGT": "E08",
               "GCAGTATC": "E09",
               "GCATGTAC": "E10",
               "GCCAGTTA": "E11",
               "GCCGACCA": "E12",
               "GCCTTAGA": "F01",
               "GCGATACT": "F02",
               "GCGTACAT": "F03",
               "GGCATTGT": "F04",
               "GGCGCCAT": "F05",
               "GGTGTTAC": "F06",
               "GTACGCAT": "F07",
               "GTCGGCTG": "F08",
               "GTGACATC": "F09",
               "GTGCATAC": "F10",
               "GTGTGCGC": "F11",
               "GTTAGCCA": "F12",
               "GTTCCAGA": "G01",
               "TACGTGCA": "G02",
               "TACTGCGA": "G03",
               "TAGAGCCT": "G04",
               "TAGCCAGT": "G05",
               "TATCGCAG": "G06",
               "TCAGTCGA": "G07",
               "TCATGATA": "G08",
               "TCCAGAGT": "G09",
               "TCCGAGAT": "G10",
               "TCGATCAG": "G11",
               "TCGCGACG": "G12",
               "TCGGCTGG": "H01",
               "TCGTAGTG": "H02",
               "TGACCGAT": "H03",
               "TGAGACCT": "H04",
               "TGCATACG": "H05",
               "TGCGCGTG": "H06",
               "TGCTACAG": "H07",
               "TGTACGCA": "H08",
               "TTACGGTG": "H09",
               "TTAGCCAG": "H10",
               "TTGACCGA": "H11",
               "TTGTGGCA": "H12"}

barcodes_384 = {}

pixelBarcodes = ["GACCTTAAGCTCTGGTACCCT",
                 "GTGACAAGAAACCTTAACGCT",
                 "CATGTGGTGAGTTCGTACGAC",
                 "ACTGGTCTCAAGGGAACAAGT",
                 "CTGGAACCTAGGGTAGAAGTC",
                 "GTTTCACGTACCCAAGTCTGG",
                 "GTTCCACTTCAGAACCAGTCG",
                 "GGTCTGACTCACGAAGCTAAA",
                 "AAAGACTGACCACTCTTCGAG",
                 "AAAGACTATGTCTCCTTGCGA",
                 "AAACGTTGCTCTCACTAGGAC",
                 "CTGACAAGGACAGTAGGTTCC",
                 "GACTCGAACTCGTCTTCTAGT",
                 "TGAGCTACGTTGAGTATGTCC",
                 "TCATGTGAGGTTGCAAATGCC",
                 "TACTCGACAGTGGATGGGTAC",
                 "ATGGTCTGTTACACAAACGCT",
                 "GTGACTGTCGAACCAGACCAT",
                 "ACCCTAGAGTCGTTGTACCTC",
                 "TCACGAAGCAAGTAGAAGTTC",
                 "CAGCTAGTTAACAGAAAGTGC",
                 "ACTAGCACTAGAGAGAGGTTC",
                 "CAGGACTTTAGGCTTAAAGGC",
                 "CAAGGATGTTGAGCTACCAGA",
                 "GACACTTCTCCATGGAGTCCT",
                 "GGAAGCTTCCAGAAAGGGTTC",
                 "GTCCACTACTAGGAAGCGAAT",
                 "AGAAACTAGGTCTTCGTACGG",
                 "AAACAGTGACTCTCTTCGTGA",
                 "CGCAACTCGAGTTTATGTTTC",
                 "TAGCAACACTCACGTAACTGG",
                 "TCTGAAACAGGAGTCACGAGT",
                 "TTTCAGGAGTCTCTTCAACCG",
                 "TTTCGATGTGACCAGAGCAAT",
                 "TAACACGTAGCACAAGTCCTG",
                 "GGCATGGTTGACACACGAAAT",
                 "CAATGTTGTTAAGCCTTCACG",
                 "ACAGCTTCGTAGTTGTGTTCA",
                 "TCGACTAGTAACAACGGAAGT",
                 "ACCCTAGGAAGCTTGTACTCC",
                 "ACGTAAAGAGCAGTTTAGCAC",
                 "TCCAAAGGAGATGCAGTTTCT",
                 "CAGGTGAGTGGAACTTAGTCC",
                 "TCTCGAGTGAACCAGACAACT",
                 "CTTCGAAGCAAACTTAGAACG",
                 "GCTTGGATGCACAACCTTTAG",
                 "AAATGACATGTCGTGAAGCCT",
                 "ACTTGTGTAGGAACCTAGCAG",
                 "ACCTGTGGTGTAGCTACTGAT",
                 "CAATGTAGTGAGCTTGCAGTC",
                 "CTATGCTCTTAGAGGAGTAGC",
                 "GGTTTACACCTTAGCGTTCCA",
                 "TGGCAAGCCAAGGTTAGTTTC",
                 "TGGCAACACAAGGTCTAATGG",
                 "TGGAACACCTACTGTCAGACC",
                 "TATGTACCAAGGCTTGCGAAA",
                 "CCGTAGTGGTAGGCTAGAAAC",
                 "CACAGCTTCCGTTAGGTCTAT",
                 "CAAAGATGCATGGATGACTCC",
                 "GTTTAACCCAAGCTAGTACGG",
                 "AAAGTCAGAAGGCTAGCCTTT",
                 "AAACTTGTAGTGCAGAGCTCT",
                 "GACCTTTACTACCGTTAGCTG",
                 "GTCACTTTGAAACGGAAAGCT",
                 "TTTGTCACTGGAAGCATGGAC",
                 "TTACGAGTAGAGCAAAGCTAC",
                 "GCTCTACTCCTTAGTTCGAAG",
                 "AGTCTCTCCTCTAGGACTGAA",
                 "ACGTTGGGTAAGACAGACCTA",
                 "GTTAGCAGAACTTTCCTCACG",
                 "CTTAGAGAGCAAGTTGCCAAC",
                 "TCTAGCTCTGAGAGAGATGTC",
                 "GTCCTGATGAGACATGCGAAA",
                 "CTTTCAGTACCAAGGAAGGCT",
                 "TTTACAGTACGCAAGGCAAGT",
                 "ACGTCTCTACCGTACAAAGTG",
                 "CAAGCTTCGGTTGATGGAAAC",
                 "CAGGTTCCAGTTTGGTAATGC",
                 "TCAAACGAACAAGTTGTACGG",
                 "CAAATGGTGTGCTACTAGCTG",
                 "CACAATGATGCTTTCGTGAGG",
                 "GTCGAGATGACCTCACTTTGT",
                 "CGAGTCCTACAAGAAGGTTTC",
                 "AAACTGACAGAGCTTAGGCTT",
                 "CTTTCGACATGAAGGGAACGT",
                 "AATGCTTGGTGTCAGTGCTAC",
                 "GACGTAGGCTTGGAGTCAAAC",
                 "CTTTAAGGCTTCACCAACGGT",
                 "CTGTTCACTGAAGGTGTAGGC",
                 "GTTTACTAACTGCTTGAGCTG",
                 "GTAAACCTACATGCTTGCGTA",
                 "TGAAACAACTAACGACTCGTG",
                 "CAGGTTAGTAGGTCTTCCGAA",
                 "ATGTTCCTTTCGTAGAGACCT",
                 "TTTGACACAGACGTCTAGCAC",
                 "CTAGGAGAGAAGTCCACTGGT",
                 "GGGAACTACGTCTCCTACATG",
                 "TCAAGCCTAACCAGAGAGTTC",
                 "TGTCAGACGATGTGGATGTCC",
                 "TGTTAGCTGAACCCAACAAGT",
                 "TTTGACATGACAGGACACGTG",
                 "AAAGCTAACGTTGGTTTCCGA",
                 "TCCGAACAGGTACCTAAGTCC",
                 "CTCGTCACAGGTTGTTAAGTC",
                 "ACCGTTCGTCTGCATGTTAAC",
                 "AAACTGACAAGAGTTGTACGC",
                 "CCACTGCTCAGAAGGTGTTAC",
                 "ACTGTTCCTGAGAGGTAGGTC",
                 "ATGCTCTTCCTAAGGTCAGGT",
                 "CGCTAACTGAGACAAACTTTG",
                 "TCTACAGGAACAATGCTACCG",
                 "AGCTGTCTAGAACAAACCTAG",
                 "CTTTCGATGGAACGTAGAGAC",
                 "GCTGTACTCAAGAACGAAGGT",
                 "GCAGTCACATGAGGAGTGTTC",
                 "ACTGTCTTTGTTACCAAGCGT",
                 "AACCGTAGTACTACTCTAGGG",
                 "TGTTTCAGTCACTACCTCAGG",
                 "TGAAACAACCAAGTTCGTAGC",
                 "TGAACACAACCTAGGACTTGC",
                 "GTACCCTTCCTTGACATGGAG",
                 "AACTTGTACTTCGTGTTCGGA",
                 "TAAGCCAACAATGTCAACGTG",
                 "GGTGTACTACGTTCCTAGAGG",
                 "TCGATGAACTGTGGTGTCCTA",
                 "TTTGAGCTAACCGAACGACAT",
                 "TTTGAGCTAGACACAACCGAT",
                 "GCAAGGTACGTTTCGTTCTTA",
                 "TTTGACTAACGGTTCTTGCGA",
                 "AAACCTGTGGAGACGTGTGAC",
                 "ACCCTAGAACGATGTAAGCTC",
                 "ACCTCTGTCAAGGAGAAGGTC",
                 "CAGTAAAGAGAGCTAAGCCTT",
                 "TGTGGACACCTCTGTTACGAC",
                 "GAACCTACCACTTGCAGTAGT",
                 "CCCATGGTACTGGTTCCGAAA",
                 "TACAAGGAAGTTGCTTCTCGA",
                 "TCAACAGTACGGAAGTCTCCA",
                 "TGAAGACTACGAAACGCATGT",
                 "CTTTCGAAAGAGCTGAGGTTC",
                 "ACTCTCGAACAGCTTAAGGAC",
                 "GGTCACACAAGAGTTTCGAGA",
                 "AGCTCTTAGTTCCTCTAATGG",
                 "AGTTCCTGACTCACTCTAGGG",
                 "AACCGTTGCTCTTATGGTTCA",
                 "TCAACGACTAAGGGAAGGTTC",
                 "TCGGAAAGGGTTACTGACCAC",
                 "CTAGTAGGAGACGTACATGCT",
                 "GTTCGAACGTAGGTGAAGTCC",
                 "CCATGGACAAGGTAAAGTTCG",
                 "CATGTGTTGCGTAAGAACCTG",
                 "TGAGTCAGCTACCCTAACAAG",
                 "AACAGGTAGTCTCTTCTCCAG",
                 "TCAGGACTGACCAAACCTTAG",
                 "CTTTCAGAAAGGCTAGTGTGC",
                 "GTACCAAACTCTCGTCAGGAC",
                 "GTCAACCAGAGACTCTTGGGA",
                 "CAAGAATGAATGCTGAATGCC",
                 "GCAGTTGCTTGGTAGTCAAAC",
                 "CGTCTCACACTTAGCTTAAGG",
                 "GCACTTCAAACTAGCTGTAAG",
                 "TGCCAAACTCTAAGAGACTAG",
                 "ACGTGTTCTCCTAGAGCTTTA",
                 "GTCGTTAGTCACTACTACGCT",
                 "CTAGAAGGAAGCGTTTACGTC",
                 "CTAGGAAAGGGTACTACAGCT",
                 "CTTCTAGGTATGCTGTACGAG",
                 "CTTTCAGTTGCTATGTAGCGA",
                 "TGTACTACACACGTTGCCAAG",
                 "TTTAGCACAAGCGTAACAGGT",
                 "CGGTAAAGTTACAACCAAGCT",
                 "CAAGGTTGTTGCTAAGGTCTC",
                 "GAAACCTAGCACTCTTCGGTA",
                 "GGGTAGCAACGGTACTATGTC",
                 "AGGTTGCTTCGTTACTAGACC",
                 "GGCAATGACCTTTGTTGCTTA",
                 "AGGTTCTGACTTCTCACTCAG",
                 "AGGTTCTTGTTTCACTCGAAG",
                 "TATGACAGAACCATGAACGCT",
                 "TTAGACGAAAGCCTAGACCTC",
                 "GTAACGACACGACTAATGGCT",
                 "GGCTTCAACCTACGTAAGACC",
                 "GGTTCTAAGTTCGCTAAGCTC",
                 "GAACTCAACCCTAGGGTTCCA",
                 "GAAACGTCTGCTCAAGTGTTC",
                 "TAGAGTCATGCTTTCCTTCGA",
                 "CTGAGTAGCACTCTCACTAAG",
                 "CTGTGAAGCACTTCAACAAGT",
                 "CATGGAGAACAGTGTTAGCAC",
                 "CACGATGTTCAGGTCTAAGGG",
                 "CGACTAGGTCTACCCTTTAAG",
                 "TAAGAACGACAGGTCTATGCC",
                 "GGTTACTACCCTAGAAACGCT",
                 "ACAACGTCTTGGAAAGTTTGC",
                 "GGTTCGAAAGCAGTTACCAGA",
                 "GACTAGTACTTGCTCTCCTGA",
                 "GAAGCGTTAACGACACAATGT",
                 "ACGGTTATGCCTAAGTACCTC",
                 "GGTCAGTTTGCCAAACCGTTT",
                 "GGACAGTACCCTTGCCTTATG",
                 "GGACACTACTCCTGTCGTCAT",
                 "AGTCCTGTAAACGCAAAGGTC",
                 "AGTGCTGTGTTGACTCTAGAC",
                 "GGACAGTCTGGTTAAGCTCTC",
                 "AGCCTAATGTGCAGTATGGTC",
                 "GACCACTATGACGTAGTTGGC",
                 "ATGGTCTTGGTACGTTCGACA",
                 "TGAGTACGAACTTCCTACACG",
                 "CACCATGAAGGCTTACGGTTT",
                 "AACATGAACTTGCGTTTCCGA",
                 "ACTGTGCTTTCTAGTTACCGA",
                 "TGGACTTTAGCCTACTTCGAC",
                 "ATGACGACAAGGTACTACCGT",
                 "ACAGGATGCAACTTCCAAATG",
                 "GTGGACTTGACCAACACTTCG",
                 "GCGAACTAGTCCTTTCCTTGA",
                 "AGTCCTACGTTGTAAGTTTCG",
                 "AAAGTTCAGACTAAGCATGCC",
                 "AAAGCTACATGGGAACGGTTC",
                 "TTCGAGAGAACACTTTATGCC",
                 "ATGTCCTCTTTAAGGGTAGCC",
                 "TTACGAACCGAAGTCTAGGAC",
                 "AGTCGTGTTGTACAAGGTTCC",
                 "AGTCTCTGTCTCTACAACGTG",
                 "GAAACCTACCTTGTGCTTGGA",
                 "TCGACAACAACTAGTATGGCT",
                 "AGTCCTTCACTATGGTACTCG",
                 "AGTCTCTACCCTTGGCAAATG",
                 "AAAGCTTTACGGAAACAGTCG",
                 "AAGCTTGATGTCTCGTACTCC",
                 "GACGTTACTCCAGACAGTCCA",
                 "CGACACTAAACCTGTAACGGT",
                 "AGCAGTTCGTACTCTTTGTCA",
                 "AGCGTACTTTGTCACTTGTGA",
                 "AGAGCTAGCAACTCTTTACAG",
                 "GTCGACTTCACAGTGTTCCCA",
                 "GTCCAGTTGACCAAACGCAAT",
                 "GTGGACTAACCTGAACCTTCG",
                 "GGCTAAAGGTTAACACAGCAT",
                 "CGAACCTAGTACTACAAGTGG",
                 "ACAACGTGAAACCTCTATGGG",
                 "ATGCGTTGAACTCTTTCCTAG",
                 "ACCTGTAGACCTTTCTTCGGA",
                 "AGCAGTTCTTAAGGGTTTCCA",
                 "CCTGAGTCAAGGTTATGTTGC",
                 "CTGCTAAAGTCTGTGGTTCTA",
                 "TTTCGTACGAACCTCTTGTGA",
                 "TTTCGTACTGGAGACAAAGCT",
                 "GGTTTACTGAACACCTTCCGA",
                 "AGTCGTTTCTTGGAATGCACT",
                 "AACGAGTTCGATGGTTACGTC",
                 "TAAGCAAAGAACGTTCTACGG",
                 "GGTTCTAGAACCCTTGAGCTC",
                 "GGCTTTACTCGTAACTACCGA",
                 "GGAGTCCAAGAGCTAGTTGTC",
                 "AGGTCTAAGTGTCCTTCGTCA",
                 "ATGGCTTCAAATGTTCTACGG",
                 "GACGTTACCATGTTCGAGTGG",
                 "CCTGAAATGGTTACGGTTCGA",
                 "AGTGCATGTTCCAACCACTAG",
                 "TTTCCGATGGACAGTAAGCAC",
                 "CTTGAAAGAGATGCAGACTCA",
                 "CGGTAAGACGTCTTTGTCCTA",
                 "AGGTCTTCCCTTAGCCTATGA",
                 "GACCACTGGACTTTACCTCTG",
                 "ACATGCAACGTTGTAGTGGTC",
                 "CCTAACGATGCTTGTGGTCTA",
                 "TACCGAACTTAGGTGAGTGAC",
                 "ACTCGTGTGGTACTTGAAAGC",
                 "TCGAACCCTAGAGGATGTGAC",
                 "CGTCAGACCAAATGAACGTTT",
                 "TTTCACGTTCCGAATGGACAG",
                 "ACCCTTGCTGAAGAAAGAACT",
                 "ACGGTTCTAACGACAGGACTA",
                 "CACGTTTCTAAGGGATGTACG",
                 "CAAATGTAAAGTGCTGAACCG",
                 "GTAGGACAACGAGTTTACGCA",
                 "TAAGCGAAACAGGTTTACCGA",
                 "AAATGTCACCTGTGCTTGCAC",
                 "CAGAGTTACTCGTCTGTACCC",
                 "CACGAGTAGAACTACTAGGGT",
                 "ACTGTCCTACGGAAGGGTTAC",
                 "CGGTTGACCAGAGTGACTAAA",
                 "CCGTTACCAGAGGTTGTGTAC",
                 "GCACTCCTACCTGAACTTGTG",
                 "TGGAAGCGTAAACACCTTTAG",
                 "CCTCAGGTAGACCAACTTCAG",
                 "GCAGTTGAGGAACTTACGACA",
                 "TACGAAACACAGGTCTCAGGT",
                 "CTTTATGGTTGAGCTAGCCTA",
                 "GTCTAGGGTAGCGTTGTCAAC",
                 "TTTGACAAGCTCACTTCGTGA",
                 "GCCAAGTGAGTTACGGTTTCA",
                 "GCTTCTACACTTTGTGCTAAG",
                 "CTTTGTACATGGTTCTACGCA",
                 "CTTTGAGTACCGAAGCAACTC",
                 "CTTAGTGTTTCCGAACTACGC",
                 "CGGTAGTACGGTAAGACTCTT",
                 "GGAGTCAGAGACCTACCGTTT",
                 "CAAGGGTTGGCTTAACTGACC",
                 "CACGTAAACTGAGAGACTGGT",
                 "GGCATGGAAGTCCTTGTCTTA",
                 "AAGGACTTCCATGTTCTCGAC",
                 "ACGGTATGTACTTTCTCTGCA",
                 "ACCTGTTGTCCTTAAGTGCAC",
                 "ACCGTATGCCTTAAGACAGGT",
                 "ACAGCATGCCTACTTAGAGAC",
                 "AGTTCTCTCCAATGTCAGACG",
                 "TAAGACCAAGACGTGAGCTTT",
                 "ACGCTAAAGTGTCTGTTACCC",
                 "GTACTCTCCACTCGTAGGTCA",
                 "CTTAGTTAGGTTTCGCAAGCT",
                 "CTTAGGTATGGTCTGTCGACA",
                 "GGAACGTATGGCTTGTTGACC",
                 "ACTCCTGTTCGTAGTAACCAG",
                 "CGGTTAGGAGTAACGTCTCTA",
                 "AGGCTAAGGTGTCAACTGTCT",
                 "CGGTAAGGTGTAACTCTCGAT",
                 "CCCTAGTTCTTGGAAACCTGT",
                 "GACTAGCAAGACCTACCTGTC",
                 "CTGGTTAACGGTTGAGACTCC",
                 "CAATGGAGAAGCGTACGTTTC",
                 "GGGTACGTAGTGCTTCCTAAG",
                 "GGGTACAGGAACGTAGCTTAC",
                 "CACCAGTGTCCACTTACTTGG",
                 "ACTGCTGACCTCTGTAAACAG",
                 "AGTTCTCTGCTTTAAGACGTG",
                 "CATGGAAGTAGGACAGTCCTC",
                 "ACGTGACCAGTGGAGATGTTC",
                 "GGAGTACCACTTGTTGCTTCA",
                 "ACGTTCTCCTACTGTTACGGA",
                 "CAGAATGGTAGTTCCTACGGT",
                 "CAGTCTGTTTGAACGAACTGG",
                 "CGTGAGCTCTGGATGTTTAAC",
                 "CCAAGCTCTAGGTTGTGTGAC",
                 "TGCCAAGGTAACCCTAACATG",
                 "CGGAAGTGGAGTACCTTTGAC",
                 "CGTAAGTGGTTGACGTTCTAC",
                 "CGTAGAGTAGGACAAGTCTCC",
                 "TCGCAAGTGAGTACTACGAAA",
                 "AGCTTCCTTCCTAGTACAAGG",
                 "GTGCAGTGTGACAACTACGAC",
                 "GGCATGAAAGACGTAACTTCG",
                 "GGATGACAAGCCTTATGCCTT",
                 "TTCGGTAAAGCGTATGGACAC",
                 "CTTGGTAACTGGTGTCAACCG",
                 "CAGGAGTAACTGGTTGCACAC",
                 "CATGAAAGAGAGTCTGTCAGC",
                 "CTAGAGAAGGGTACAGCTTTC",
                 "CGGTTAGTCTTGTAGCAACAT",
                 "GACGTACTAGCACTTCCAGAC",
                 "ACAAATGTACCGAAGTTGCGA",
                 "ACGCTTCTTCAATGTTACAGG",
                 "AGTGTTCAGCTTTCCAACAGT",
                 "AGGTTCTCTCTAAGCTACGTC",
                 "CTCTGAGGTTCCACAACAATG",
                 "CAGTGTAGGAAGCTAGTCCAC",
                 "ACGTGTTGAATGTCAGTTCCT",
                 "CTGTAGTTGTGGACTCGAACA",
                 "CCTAGCTCTGTGAGTAGTTAC",
                 "CGAAAGTACTGGTGAGTCCTC",
                 "CAGTGGTTAGAAACAACGCTA",
                 "CGTGACTGCTACTAACAAATG",
                 "GGCTACAAGGTCTTGCTGTTA",
                 "GTCTTCAACGTGTGGAGAGTC",
                 "CTGTCGAACAGGATGGAGTTC",
                 "GCGTTAGTTGGAACTAGAACC",
                 "AGGTCTATGACAAACGCAACT",
                 "CTGTTTAGTTTACCTCAAGCG",
                 "GGTCTAGAGCTCTACTCGTTA",
                 "TGGCTTATGGCTATGACTCAC",
                 "CCTGAATGGAAGTCACGTAAG",
                 "CGTGAAGAGACAGTCACTGAT",
                 "CAGGAGTGGAAGTCAGTACCT",
                 "CCGTACTTCCTGTAATGTCGA",
                 "CCGTTTACGTTTAACCAGTGG",
                 "TCCAAGGCTTAGGGAATGAAC",
                 "CGCTAACCATGGAGTAGTTTC",
                 "ACGGTAAGCTTTAACCCTTAG",
                 "CGTTAAAGTGTGACAGGTCTC",
                 "CCGTAAGCATGTTGTTGTTCA",
                 "CCCTAGAATGTTGCTTTCTGA",
                 "CGGTTTAATGAGTCAAGCCTA",
                 "TCGGTAGGACTACAAACCAGT",
                 "CTAAGAAACAAGCTGTCAGGT",
                 "GCACTCTCTCTATGTAGCAAG",
                 "CTGGAGACTGGAAGGTTTACC",
                 "CCACAGTTTGCGTACTTGGTA",
                 "GCTACACCTTAAGGTTTACGG",
                 "GCTATGCCTTGGGAAACAATG",
                 "GGCAATGCTAGTAGGATGACC",
                 "ACCGTAGCAGTGATGTTGAAC",
                 "GACACCTTAAATGCATGCGAA",
                 "GACTCCTTCTCTAGTGCTAAG",
                 "GAACACTCAACTGTCCTGAGC",
                 "TGACACACTCTTAGCTAGGAC",
                 "TGAACCACTTATGCTTGTAGC",
                 "ACGTCTCAGCTTTGGTATGAC",
                 "GAGTCTCTCGTCTATGCTAAA",
                 "GCTCACTGTCGTTACATGAAA",
                 "GTTCTTACTCTACGAAGTGCA",
                 "GTTCCACTACAGAGACAACGT",
                 "CATGAGGTTTGCTAACTTCGG",
                 "CGTTCGAAGTCCTTCTAAATG",
                 "GACCTGTCTGAGTGTTGGAAC",
                 "GACCACTCTGAGAGGTTGTCA",
                 "AGTTCCAGAACCTACCTAGGC",
                 "CCAGTAACATGGTGTGTTCGA",
                 "TGCAAGCCAACAGTTAGACTA",
                 "CGGTAAGAAGGTACCTAGCTT",
                 "GCAAACTCTCTGTACTCTGAG",
                 "GCTACACTCCTATGACGTGTC",
                 "GCACTGTCTCGTTATGCTTAA",
                 "GCTTTCACCTCATGTGGACAC",
                 "CTGGAACGTTCAACCCTTTAG",
                 "GTCTCCACTAAAGAAAGCGAT",
                 "TTGTGCACAAAGTGAAGACCT",
                 "GTCGATGGTTCACCTTAAGCC",
                 "CTAGTGTTGGTAGCTCTACAG",
                 "GGCTAACGTAACAACCCTTAG",
                 "GACGATGTAGCTGAGTACCAC",
                 "GAGCTCTCAAGGTGTTTGGAC",
                 "GTCTCCACTCTAAGCTTGTGA",
                 "CCCTAGTTGCCAAAGTCAAAG",
                 "GACACTACCCTTAGACTGAGG",
                 "GTACACTCTCTGGACAGGTGT",
                 "TAGCGATGCTTCACAACTATG",
                 "TCCTAGGGTACAACAACACGT",
                 "TGGCTACGTTTCTACCAAAGT",
                 "GCACACTTTAATGCAACTGAG",
                 "TCCGAAGTCCAGAACAGTAGT",
                 "GTCGTACAGTCCTAATGCTCT",
                 "GACTTACCACTCAGCATGGTG",
                 "GTTCTACCACACGTGTTCCAG",
                 "GGTAACCAACGAGTTCTGAGG",
                 "ACAAGTACAAGCGTTATGGCA",
                 "ACGCTTCTTGTCTACAAGGTT",
                 "ACCTGTCGTCTCTAACATGTG",
                 "AGGACTGCAAGTTAGAGTACC",
                 "GTACACTTCTTGAGGTTGGCA",
                 "GTGATGCGTTCCCAACTTTAG",
                 "CTGATGACAGTGGAGTAGTCC",
                 "CTAGGGAAGGAACTACGGTTC",
                 "GTAACGAGTCTCACCTCAAAG",
                 "GTGTGACGAACTCTTCTCTGA",
                 "GTCAGCTCTGAGGAATGAAAC",
                 "GTAGTGCTCAGGAGTGACAAC",
                 "GTGGTCAAAGCGATGAACCTT",
                 "GTAACACCACAAGTCTTGGCA",
                 "CTGTTAGTGTTACCGAAGCCT",
                 "GTAACCAAACCATGCTAGCTG",
                 "GTGGACAACTAGGCTAATGGC",
                 "GTAAACCCAACCGTTGTACCG",
                 "GAATGTCCTGTCCAACTGGTG",
                 "GTCAACCCTTCCAGTCTGAGA",
                 "CATGTTTGAGGTTCGTCACAC",
                 "TGTCCTATGTACCTGTACGCA",
                 "TGAGCTCATGTCCTTTAACTG",
                 "CGTAACTGTAACCCTTTCGGA",
                 "GGGAACTGCACTTTCACAATG",
                 "GGGTAACGTGACCTCATGGTT",
                 "GAGGTACACGTTTCTCCTTGA",
                 "GACCTACTAGTCGTCTCCTGA",
                 "CAGAGATGTGTGACCTAGTCC",
                 "GTCGAAGATGTCCTCTCTATG",
                 "GTGTCCACAAGGATGAGTTCG",
                 "TGTGCATGAACTCACCAACTG",
                 "GTGCAACACTCCTGTCCTATG",
                 "GTCCATGCAGTCTTCTACTAG",
                 "CCAACTGAGGTTCTTGCTCTA",
                 "GTCCTCAGAAACTCCACATGG",
                 "TGGGAACACCTGTCCTGTCTA",
                 "CTAAGAGAAATGGCTTCCGAA",
                 "CAGAATGAGGAACTGTTCCGA",
                 "CAGAATGATGGAACTGCTTCA",
                 "GAGAGCTACCCTTGACACATG",
                 "GGTTCCACATGGTGTAAAGGC",
                 "GTACCTCACCTCAGCAGTTAG",
                 "GTCAACTCACTCGACTTGGAG",
                 "GTCATGTAGCTTCTCAACTCG",
                 "CTAGGGTTGCTCACTCAGAAA",
                 "CTTGGAGAGGTAGCTGTACTC",
                 "CTTTGTACAAGTGGAGTGCTC",
                 "AGTCGACTCAAGAAATGTAGC",
                 "CAAGTGTTGTAGTCCTACGGT",
                 "CGACTTCGTCACAACAGGAAT",
                 "CGACTTGTGAACCACAGAACT",
                 "CGTTAAAGGGAACTCGAGTAC",
                 "AGCTTGTTGTTAACCTTCAGC",
                 "CAGTGTTTGTTTACCATGCGA",
                 "GCAGTTTGGCTTTAGTACCAG",
                 "AGGCTAGGTACCTTCTTAACG",
                 "CTGGAAGGACAACTTTCACTG",
                 "TAGACTGGTACCCAACTCCTG",
                 "CAGGAGTGTTTGCACAGTTTC",
                 "CTGGAGTTTGTCGAACTACGA",
                 "CGGATGGTGTGAACTAACCTG",
                 "CTGGATGGAGTGACGTAAACC",
                 "CGCTAAAGCATGAGGTTAAAC",
                 "GCCTAGGTTGGAACGTACAAA",
                 "TGCCTACTGGAAACAAACGAT",
                 "CTGCAGTTAAGACAAGGATGC",
                 "GGGTAGCCAAGACTTACCAGT",
                 "CAGTTGGTGTTGCACATGGAC",
                 "CATGTTGAGGAGTCCTGTGAC",
                 "GTCTGCACAGAATGAGAGTAC",
                 "GTCGTGACAAAGTGTGGAACC",
                 "CGACTTTATGGACAGACGAGT",
                 "CGAATGGTAGAACACACCTTG",
                 "CGTTCTAAGTACAACACGAGT",
                 "ACTGGTTTGTTGACAATGCCT",
                 "AGCAGTCGTTAACAACTACTG",
                 "CTAGTTTGTTTGACCTGAGCA",
                 "AGGCTTACTCAAAGTACGACA",
                 "CATGGTAATGTTCGTCTAGCC",
                 "CGTGTAACACTAGAACACTCG",
                 "AGCTGTACACACGTAAACCTG",
                 "GAGCTTACATGGAAGGAACCT",
                 "GTCTAAGTAACAGCAAAGCCT",
                 "TCGCAACGAACAGTTACTTTG",
                 "CGAGTTAGAAGTTCCAAGCAT",
                 "TTTCAGAGCACAGTACTCAGG",
                 "CGTGAAGGAAGACTTGAGTCC",
                 "CATGTTAGTGAACGGAACCCT",
                 "CTCCAAGAAATGCAGTACTGG",
                 "GTACAACCAGAACTAGGCTTG",
                 "GCTACAACAAAGGTAGGTCTG",
                 "CTTGCAGTCAAAGAAGGGTTC",
                 "TGGTCAGAGGACTAAACGACT",
                 "CTCCAGTTGAACGAAGAGACT",
                 "ACTGTCTCTGTTAAGAATGCG",
                 "AGTTTCCTCTCAAGAGACTCG",
                 "GGTGTACGTCTACTCACTACG",
                 "CTGCAGAAGGTAACAAGCTTT",
                 "TTGGCTACTCCAGTACAAAGT",
                 "TCTTGCACTTAAGAGGTAAGC",
                 "TCGCTTAGCTTTAAGAGGTTC",
                 "CGACTCAAGCTTGTTTAGGTC",
                 "CGTTGGAAGAACCTATGCAAA",
                 "CATGAGAGGAATGCAACTTGC",
                 "CTCATGTATGTCGTGTACCGA",
                 "CTTCGACTCAGAAACAGAGGT",
                 "TTTAGACTAGCCAACACGTGT",
                 "CATGGTGAAAGGCTTAAACCG",
                 "CCTCAGTTAGTCCATGAACCG",
                 "TCCCATGTGAAACTGAACGGT",
                 "CTACAGTCAAGTGGAGAGGTC",
                 "CTGCTACACTGAGGTAAAGAC",
                 "CTTATGGAAGGACTCAGCTGT",
                 "CCTAGGAAGGCAATGACAGTT",
                 "CCTTCGAACGAATGAATGGAC",
                 "GCCTTACTACCAAGAGGTGAC",
                 "GTCACCAACTAAAGCTGATGG",
                 "TGTCCAGTGGAGTCAGGTAAC",
                 "TTGACGACAAAGATGCCAACT",
                 "CGGATGTTAAAGACACAACGT",
                 "CGTGATGTCAAAGCCAAACTG",
                 "CAAGAATGAGTTGCAAACCGT",
                 "CTGAGGAAGTAAACAGTCGTC",
                 "GTCGAAGTCGAAATGGAGTCC",
                 "AGCCTTCTGTCTAGACTTGAT",
                 "AGGTTTCTTGCTGATGACGAC",
                 "ATGTGCTTTCCATGTACACGA",
                 "AGTGTTCTCCATGCTTCAAAG",
                 "CGCTAACTAAACAGAGGACTT",
                 "CGACTAGCATGGTTTGGTTAC",
                 "GCTGATGGTGAGTCAATGTCC",
                 "CTATGGTGTATGCAGTACCCA",
                 "CCGTAAATGAAGACGAGTTCT",
                 "CTCGTACTAGGACAAAGACCT",
                 "CTCGAGTTGACCTTAACCATG",
                 "CGAGAGTAAGTCGTTACAAGC",
                 "CCAAATGCTAGGAGAGTGGTC",
                 "CTGCTACCAATGGGAATGGAC",
                 "CCCTATGTACGACACAGAGTG",
                 "GGGTACGGTTTCCACACAAGT",
                 "TCCTGTATGACACCAAGGCAT",
                 "AGTTTCTAGTCTGACTTCCGA",
                 "AGACTTCACCTCTGGTACTGG",
                 "AGAGCTCAGTTTCCCTTTATG",
                 "CAACTGGAGTTCTCCTCTTAG",
                 "CGAGTGGAGTAAACTTCCTAG",
                 "GACCTACTTTAGCAGACGTTG",
                 "TAGCCTACTATGTTGATGACG",
                 "AGTTCTCTCTCTAGTGACGAT",
                 "AGGTCTCCTTCATGTGACAAG",
                 "TCGGAAGTTTCTAGAGTCTCC",
                 "CTGGAAGTAGAAGCGTAACTC",
                 "GACCTACCCTTAAGGACTGGT",
                 "CCGATGTAATGTTCTAGGCTT",
                 "CAATGATGGAGTGCTTTCAGC",
                 "CTAGGGATGGAGTCACACTGA",
                 "TCCGAAACAGAGTTAAGTAGC",
                 "TCCCTAGACCAGTGAAAGCAT",
                 "CTGGTCATGAACGAACAACTG",
                 "CCCTAAGTAGTCGTTTCGTGA",
                 "CGCTTGATGAACCAAACAATG",
                 "CGCATGTTGTACCACAAGAAT",
                 "ACAAATGAACCGTTGGTCAGG",
                 "TCAAGGCAAGACGTAATGGTC",
                 "CAAAGCTCAATGAGGTATGGC",
                 "GACAGGTTACGGAAGAGTCCT",
                 "TCAGGTTACGAAATGCACTCC",
                 "AGACACTACTTTCGCTTGTGA",
                 "GAACTCAAGTCGTCTCTTCGA",
                 "CGTCAGTTGTACCAAAGCCAT",
                 "CAGTAGGTGTTCCAACGTCTC",
                 "CGTGAGGTTTGAACAGCTTTC",
                 "TCCGAAGTTTCGAAGACTCAC",
                 "CCCAAGTTCCGTTAACACTGG",
                 "CCGTAGTACCAAGTACACCTG",
                 "CAAGCTACGTAAGGATGGTAC",
                 "CCTGTACCTAGTGGAAGTAGC",
                 "AGCCTTGACTTGTTGAGGTAC",
                 "CAAGCTTAGTCTCTTGGGTAC",
                 "CACAGGTCAGTGTTTGGTTCA",
                 "CTAAGTTGGTTCGATGTGCAC",
                 "CTAATGGTAGTACGCTAAGCA",
                 "CGTGATGGTTGAACGTCAAAC",
                 "CCTCTGAGTGGACAAGCTAAA",
                 "GCTCTAACTAAGAAAGTAGCG",
                 "CCAGTAACAGTGGAAAGGCTT",
                 "CCCAATGTCTGAGGTAACAGG",
                 "CCCTTAGAGACCTAAATGACG",
                 "CAGTAGTGTAACCCAAGACGT",
                 "CAAAGCTGACTGGTTCTGTGA",
                 "CTGGAGTTACGAGAGTACCAC",
                 "CACGAGTCTTGGTAGGAGTTC",
                 "CGGTTATGCGTTCAAGTCAAA",
                 "AGTGTTCTCGTGAGGTCTCAA",
                 "TAGCGAACCCAATGACTTTGT",
                 "GAGCACTCTAGGTTTGTTCGA",
                 "CATGAGGTTGTAGCTAAGACC",
                 "CTAGTTGGAAGGCTTCAAAGC",
                 "CGTGAGTTTGTGACACCTGTA",
                 "AGGTTCCCTTGTTATGAACGG",
                 "TCCAGACATGCTTTGGGTACT",
                 "TCCCTAGCGTAAAGAGAACAT",
                 "CAGCTTTCGTCTGAAGTCAAA",
                 "CAAGCGTATGTCGTTTCTGTA",
                 "CACAGGTAGTTCTTCTGGTGA",
                 "AACCATGACCTGTCGTTCGTA",
                 "ACGACTACATGGTTGGAGTTC",
                 "TCGTGTACTGAAGAACGCAAT",
                 "CGTGTACTACAGGAAGCAGAT",
                 "GGTTCTAGGTTGCAAGTGACC",
                 "GGGTTACTGTCGTACTAAGCC",
                 "CTGGTCAGACCACTTCACTTG",
                 "TAGGCTAGTCACACTACTCTG",
                 "CAAAGTTGCTACTCCTTGTGA",
                 "TCCAGTCGTTTCACTTACAGG",
                 "CCAGTTTGTCCTCAACTAGGG",
                 "AAACTTGCTAGGTGTGATGCC",
                 "ACAAGCTCTGTAGGGTAGGTC",
                 "CGAGTCCAACTTGTTACGAAA",
                 "CAGTGCAACCTGTTTCTTTGA",
                 "GGGTTCAAGGACTCTAAGACG",
                 "TACAAGGGAAACGTTTCAGCA",
                 "CGTCTGAGTCAAACAAACCTG",
                 "ACGCTTTCTTTATGTCGAAGG",
                 "ACCTTGCTTGCTAATGGTTCA",
                 "CCAGTTTGTGCTCAAGGTTCA",
                 "GAGGTACTGTCCAAGAACCCT",
                 "AGGGTACGAACTCCTTTACAG",
                 "ACAGTGTGACTTCCTTCTCGA",
                 "GACAGCTGACACTTCCTTTAG",
                 "CACACGTTTGACCTTATGTGC",
                 "CCTGTGAATGTTCCTTCAACG",
                 "CATGTTGTTTGTCAGCTCACA",
                 "GTCCAGTCGTGTTAGAGTAGC",
                 "ACATGCACTTGAAGGTTAGGC",
                 "TCCGAACCTAGAGGTGTTTAC",
                 "TTTCGAGTCGAGAGTCAAGAC",
                 "TTTGTCAAGTCCACTCTGCAG",
                 "GTCTTAAGTACACCAGAGCTG",
                 "GTCGTAAACGTCTCTCTCGTA",
                 "TCCTTGACGAGAGTAGGGTAC",
                 "CGGTAACCAGTTGTGTCGTTA",
                 "GAGGTCTACCGTTATGACGTG",
                 "ACTACTGACTGTTGCTTGGGA",
                 "GAGCTCACAGGTGTTCGTTTA",
                 "ACCGTTGTTGAGTCTGGTAAC",
                 "ACGTTGGTTGGTCAAGCTAAC",
                 "AGGACTCCTGTAGTGATGGTC",
                 "CTGCTACCGTAAGAAGAGTAC",
                 "TTTCACGTTGTCGATGGCAAA",
                 "ACACGTTGTACCCAAGAGACT",
                 "ACCGTTGTAACGAGAAGGTCA",
                 "ACGCTTCTTAACAGAACGGTA",
                 "TCCGTAACTAGAGGAAGGACT",
                 "ACCAGTCCAATGTTGTATGGC",
                 "AAGTCAAGCTTACCTCTCAGG",
                 "CTGTCCAACGACTACTAGGTG",
                 "TTTCGCAACGGTTTAGTGTAC",
                 "TAAAGCTTTCCGTACCAGTGG",
                 "CGTACTCCTCAAAGAGTGGTC",
                 "GCCTACTTTCCAAGGTCAGTC",
                 "ACCTCTGTTTCGTAACGTGAG",
                 "CGAAAGTAAATGACGTTACGC",
                 "CAAAGTGAAATGACACGTTCG",
                 "GTTCGGATGGACACCAGAGAT",
                 "GTTGTCACAGACTCCAAAGCT",
                 "GTTGTCACAAGCCTAGTACCC",
                 "GTCGTAACTAGGTGTTCGCTA",
                 "GGGTAACTCTTGGACTCGTGA",
                 "AACGGTTAGCCTTTGTTCTCA",
                 "ACCTTGGTGTTCTATGACGAG",
                 "ACGTTCTTTACTTGCATGGAG",
                 "AAAGCGTTTCGGTAGTCACAT",
                 "AGATGCGTTGGTCAACTTGTC",
                 "CCTAGGTTGTAAACTGTGCAG",
                 "CTAAGGGTTAAGACAGTCAGC",
                 "AGTTAGCTTGTCGACTTGACC",
                 "CTTAGGGTTGGAACTCACGTG",
                 "ACTCAGACTGATGGTTATGGC",
                 "ACTACTGCTGAGTGTGTTGAC",
                 "ACTGCAAGCATGAGTAGGTAC",
                 "AGGCTTGTGCTTTACGTACAT",
                 "GTAGCCTAGTTCCTTTACACG",
                 "GGAGTTCCTGAGTTAGTGACC",
                 "CATGGTGTTGCTTACTTCGAA",
                 "GTGTCCAGTTTACACTTCCGA",
                 "ACCAAGTACGGTTTGTGAGTC",
                 "CACTGTCTCCTATGCAGAATG",
                 "CAGTTCTCAATGTGCATGGGT",
                 "CTGGTAGTTTAGTCCTGACCA",
                 "CCCAAGTAAAGTTCTGGAAGC",
                 "GTCCTGACGTTGGAGTTGAAC",
                 "CACGAGTCGTATGGTAGTAAC",
                 "CCTGAGTTAAGTGCATGTCTG",
                 "GCTACCCTTTCTAGGTTCAAG",
                 "ACTCGTCTCTTAAGGTAGGAC",
                 "GATGCAAAGCTTCCCTAACTG",
                 "GAAACTTCTTCTAGCTAGACG",
                 "ACGGTTCCAGAGGTGACTAAA",
                 "TGACGAAAGGTTCCTTCACTG",
                 "AAACTGTCTGAAAGGAAGCCT",
                 "ATGGTTCGACTCAACAACCGT",
                 "CTGTTTAGCCAACTCAGAGGT",
                 "ACGTCTTGGTCTTACAACTGC",
                 "TACAAAGAAACGGTAGCTCTC",
                 "CCTGTAAACTTGGAGAACCCT",
                 "TGAAGCTTGAACACACTAACG",
                 "GACCTTTACCTTTGCAGTGAG",
                 "GACCTAACACCTTGTGAGCTC",
                 "GCAAACTCCTTCAGTAGACAG",
                 "CACTAGTCAGTAAAGGAAGCT",
                 "GACTTTACTCAAGGGTAGCAG",
                 "ACTCTGTTCAAGGGAATGAGC",
                 "CTAAGGGTTGTGCACAGTCTC",
                 "TTTAGCACTTGAGGTTAACCG",
                 "GTCTCTAGCTTACCCAAGGGT",
                 "GTCCATGAGAACGTGAGCAAT",
                 "TAAACTGATGGCTTCCTAGGG",
                 "TGACCAGAAGGTTCAAACGGT",
                 "TGGTCAAAGTTCTCCTTCGGA",
                 "ACTTGGTTGCTTCAGACTCAA",
                 "AGGCAATGTCACTCTAAACAG",
                 "AGCGTTGTAGCCTTAACAGTA",
                 "CTGAGTAGTGAACGAACCGAT",
                 "GGACTACTAAGCCAACCTTGG",
                 "CAAATGGGAAAGTCTGTAGCC",
                 "TAACAAGCACACGTGAGGTTC",
                 "CGTCAAACAAGAGTGGATGTC",
                 "CGTAAGGCAAAGGTGTGTACC",
                 "GTCGTATGTTACTCCAACTCG",
                 "CTAGGATGTTACCACAACCGT",
                 "ACCGTTTCTCCAGTCAAGGTC",
                 "CCAATGACAATGGTAGTGAGC",
                 "GTTTACCCTTCACGTAACGGA",
                 "TACCTGAGTGTGCAGTCTGTA",
                 "TCGCAAGTTGGACTACGTAAA",
                 "ACTGCTTCAGGTAGTAAGGTC",
                 "CAGCTTGTCAGAGAAACAATG",
                 "GACTTCTTGGCTAAACTGCTG",
                 "CGTTAGAGAGAGTCCAAGGTC",
                 "GCTCTGACTGGAAGAAAGTAC",
                 "CCGATGAACAAGGTTGTCTGA",
                 "CCCTATGAATGCAACAGGTGA",
                 "ACTGTTGGTGTTCACTGCAAA",
                 "ACTTGGTGTGTTACTGCAGAC",
                 "CCTAATGTGGAGACTGAGACA",
                 "CCGAAATGCGAAATGGTGTAC",
                 "GCCTACTTCTAAAGTGGTAGC",
                 "ACTCCTGTGGTAACCTTGTGA",
                 "CCCTTAGAAGTGTCCATGGTG",
                 "TACGCAAGAAACTCTTTCAGG",
                 "CTGGATGAGATGACACGTCTC",
                 "GCTTTGAAGTTGTCTACGCTA",
                 "TCAGCTATGAACGAGAGAACT",
                 "CGCTTTATGCAGAAGACCAAT",
                 "ACAGGTAGACTACTCCTTCGA",
                 "GGGAACTTTCCGTAGTCCTGA",
                 "GACGTCTCATGGATGTTACGG",
                 "GTAAACGGTACCTCTTTCGCA",
                 "GAGTCACCAGTTGGATGTGTC",
                 "GACGTCTCTTGAAGGATGGTC",
                 "GCACTGTTTAGACTTGAGAGC",
                 "CAGCTACGAGTTTCTACTTTG",
                 "ACCCTAGTGTTCACACTCTGG",
                 "ACCCTTGGAGTCTTCATGAGG",
                 "CAAGGTGTAGTGTCCACAGGT",
                 "CAGTGGAGAGAACTCTGAACT",
                 "CCACTGTCAGTTGAAAGTAGC",
                 "TACCGTTCAGTAGAAGATGGC",
                 "AGCGTTCAATGGACTGAAACA",
                 "CCTAATGACGTGAGAAGCAAT",
                 "TCGGATGTTTCAGAGTTCCCA",
                 "ACTTGTGGTTTGACTCTACGA",
                 "GACTGTTTCACACGACACCTG",
                 "GGAGTCGAAGGCTTAATGACC",
                 "CATGGTTGCCTTCACTTCAAG",
                 "TAACCAGAGCACTCCTAGTTG",
                 "GACGACTTGGATGCTATGGTC",
                 "ACTTGTACAGGTGTTTCTCGA",
                 "AGTCCTTCTGCTTAAAGACTG",
                 "AGACCTTCTGTGTAGTTGACG",
                 "AGACCTAATGCTGTTGTCGAC",
                 "TGCAAGGAAAGTTCTGACCAA",
                 "GCAACCTAAACTTGACCTAGG",
                 "CCTAGTGTGGATGCAGATGAC",
                 "CCATGGTATGGTTCAAGCGAT",
                 "AGCTTGTTCCTCAGTTCAGAT",
                 "CAAATGTTCCTGATGCTCACG",
                 "CCTCATGACTGGAACTAGGGA",
                 "TCTGGACTACAGGACTAGGAG",
                 "AGGCTTTCATGGAGTTGACTC",
                 "CAGGTGTTCTCTGAGACTACC",
                 "ACGGTTCTTATGTCCTACAGC",
                 "ACAGCTCTGTTTCAGTTGGAC",
                 "CACACTGTCCTGTAGTTGCAC",
                 "GAACGCTACTTGTCTGTTTCA",
                 "TCCAAGGGAAAGCTACAGTTT",
                 "GTAAACTCACTGCTCTACGGA",
                 "CTTGAAGAGGATGCATGAACC",
                 "CATGCTTGACTCCACAAAGGT",
                 "AAATGCTCTGCTCACAAAGGT",
                 "GACTGCTCTAAGGGAAACAGT",
                 "CAGAGATGTAACTCCTACAGC",
                 "ACAGAGTTCTGGAGTGTCCAC",
                 "AGTCTGTTCTGTCAGATGACG",
                 "AAGTGTCATGCTTCGTTGGAC",
                 "GTAACCCAAAGGCTTTAGGCT",
                 "GACTCTTAGTCGTTTGAACGG",
                 "TGGAAACCAAAGGTGTTCCGA",
                 "TGAAGCCAAACATGATGGTCA",
                 "TGAACAAGAGAGCTCATGGTC",
                 "GGATGCTGTCACTTCACCTAG",
                 "TGCAGTCAGTCTCCTAACTTG",
                 "TTACTAGAACTCGTGTGCTGA",
                 "GTAACCCAACCTAGGTGACGT",
                 "TCCATGGCTAAGAGACAAGGT",
                 "GCTCTAGCACAGTAACAAGGT",
                 "CAGAAGTTGGAAGCACTCTGT",
                 "GTAACCCTACTTCGTGAACGA",
                 "TGGCAACTACGGAACATGTTT",
                 "CGACATGCTATGTTGTGGTCA",
                 "ACCTGTCCAGAGTGTTTATGC",
                 "AGACTCTCGATGGTTGTTAGC",
                 "AGAGTCTCGTGTGAGTTTCAC",
                 "CACAGCTCATGGGTTTGTTAC",
                 "CACCTTGACTGTGATGTCGAC",
                 "CACAATGTGCAGAGAGAGTTC",
                 "TCAAAGAAACCATGTGTGCAG",
                 "CGGTACTCTCAAAGTGCTTTA",
                 "CCAGTAGGTTAAACAAGCGAT",
                 "TCTGGTAGCTTAAACTCAACG",
                 "CTCGAAGTCGTGTAGTGAAAC",
                 "TCAAAGGGAAGACTGTCTCCA",
                 "CACCTTGAAGTGCAGTGAAAC",
                 "CGTGTAGTAGAACCAGACTGG",
                 "CCTGACTCTGAGAACGAGAAT",
                 "AGCTTCTCAGGTGTTGGTAAC",
                 "GCCTACTCCTTTGACAGTAGT",
                 "CAGCTTGTAGGTCTTGGGAAC",
                 "ACCTGTTGCTGTTAGGCTAAA",
                 "ACGACTTTGCAGAGAACAGAT",
                 "CCTGAGTTTGAGACAAGGACT",
                 "AGTTGCTTCGACACACAAGAT",
                 "AAAGTCTGTCTCCAGTTGCAC",
                 "ATGCTGTTCGAACAAGACAGT",
                 "TCCGATGAAGCGATGTACAAA",
                 "AGGTCAGGTACTCCTTCTGTA",
                 "GAAACTGGTACTTCTTTGCGA",
                 "GCTTCTATGCATGTCTACCAG",
                 "GCCTTCACAACGGTAGTTCTC",
                 "CTGTTGATGTGACTCTCGAAA",
                 "TACAAAGAGGTAGCCTTACCG",
                 "GCCTTTACTTTAGTAGCGTAG",
                 "CTGGTAGTTAACGAACTCACG",
                 "CGGTAGTTGAATGCTAGACCA",
                 "CAGGTAGTCAGGTCTGAAACA",
                 "ACCTGAGCATGGGTTCTGTTA",
                 "CCAAAGTAAAGTGCAACGTGT",
                 "ACTTGTTTGTGTACGTCAGCA",
                 "TACGGTTTAACAGCAACAGCT",
                 "TTCGGTAGCTACCACAACATG",
                 "CCGTTATGCTACCACAGAGAT",
                 "ACTTTAGTAACACGAGAGCTC",
                 "TTAAGACTGACAACCAAGGCT",
                 "CCTGAGTCAGAGTAGAGGTAC",
                 "GACAGGTCAGAGTTGTATGCC",
                 "GGCAAGTCACTGGTTTACTGG",
                 "TTACCGTTGAACCAAGGAGTC",
                 "TCAGTGTGCTACCTACCTAAG",
                 "CTATGAAATGTGCTCTGGACT",
                 "CTGGTTAGGTGACATGTAGCC",
                 "CCGTTAGGAAAGTCATGGACA",
                 "CGTTTATGTGGAACCATGTGC",
                 "CTTTGTAGTGTGCAACATGGC",
                 "GTACCCTAACTTTGGATGCGT",
                 "CTCCTAGTAGACTACGAGTGG",
                 "CCTCTAGTGAGACAACACAGT",
                 "GCCATGTACGAGTAGGAGTAC",
                 "GATGCACAAGCTTTCGTGTTA",
                 "GTGCAAGCACAGTTCTAGAAA",
                 "CTCACTGGTCAAAGGTACACC",
                 "TCTCGTATGGCAAGAGGTAAC",
                 "TTTGCTATGAGCAGAACGTTC",
                 "CCTGTTACAATGAAGAAGCGT",
                 "CTAGTAGAGGAGTCGAGACTC",
                 "CGAAAGTGAGGTTCTGTACTC",
                 "CGTTAGTTGTGTCAGCAGTAC",
                 "ACTGTCTGACTACCAAAGGCT",
                 "CAAAGTTGTTCTGAGTAGCCT",
                 "CCTGATGCTTGAGTGAGGTAC",
                 "GCACTAGCACACTGAGACTAT",
                 "CCCTTAGTGCAGAAAGTGGAC",
                 "CTTTGATGTTTGCAAGCACTG",
                 "CCTGTACTCAGAGAGACAAGT",
                 "CTCTGACACTTGTGGAGAACT",
                 "TCACGTTCTGAGTGTGAAGAC",
                 "TTTAGTCTACGCAACTTCGGA",
                 "CGAGACTGTGTACGATGTTTC",
                 "CATGCTGACAGGTGATGGTTC",
                 "CACCATGCTTTAGGTATGTCG",
                 "CTAGTGGAAAGTGCTGTGACC",
                 "TTTAGGCAAACGTGTAACTCG",
                 "CTATGTGAGAGACTAGCGTAC",
                 "CGGTAAGTATGGTCAGACACT",
                 "CTATGTCCTTGGTATGGAACG",
                 "CTTAGTAGGAAGTCGAAGTCC",
                 "CGTGAGAGGTTTACAACGTCA",
                 "CGAAGGTTGTTTACACAGTGC",
                 "TCTCGAGAGTTTCTCTACATG",
                 "CCTAAGACTATGAGGAAGCTG",
                 "CCGTATGACTGTGTGTAGGAC",
                 "GCACAGTTCGGATGTATGGAC",
                 "GCACATGCTAAGTGGAAGTTC",
                 "TTGCGTACGTGATGTAGAACC",
                 "TTCTGTACGAAGGTAGCACTC",
                 "ATGCGTTCCTTCAGGACTTAT",
                 "TTGTCAAAGGTCTCGTTGCAC",
                 "TCGAAAGGGTTTCAACAGTGC",
                 "GTTTACCCAAAGGTGACGAGT",
                 "CTGTCTATGACCAAGAAGGCT",
                 "GCTACCAACAAAGTACCGTTG",
                 "CCAGTTCGTAACACCAGAATG",
                 "GCTCTGACATGGATGGTTTCA",
                 "TGCACACCACAATGGTCAGTT"]

TCR_alpha = ["TRAV1-1",
             "TRAV1-2-01",
             "TRAV1-2-02",
             "TRAV2",
             "TRAV3",
             "TRAV4",
             "TRAV5",
             "TRAV6",
             "TRAV7",
             "TRAV8-1",
             "TRAV8-2",
             "TRAV8-3",
             "TRAV8-4",
             "TRAV8-5",
             "TRAV8-6",
             "TRAV8-7",
             "TRAV9-1",
             "TRAV9-2",
             "TRAV10",
             "TRAV11",
             "TRAV12-1",
             "TRAV12-2",
             "TRAV12-3",
             "TRAV13-1",
             "TRAV13-2",
             "TRAV14",
             "TRAV15",
             "TRAV16",
             "TRAV17",
             "TRAV18",
             "TRAV19",
             "TRAV20",
             "TRAV21",
             "TRAV22",
             "TRAV23",
             "TRAV24",
             "TRAV25",
             "TRAV26-1",
             "TRAV26-2",
             "TRAV27",
             "TRAV28",
             "TRAV29",
             "TRAV30",
             "TRAV31",
             "TRAV32",
             "TRAV33",
             "TRAV34",
             "TRAV35",
             "TRAV36",
             "TRAV37",
             "TRAV38-1",
             "TRAV38-2",
             "TRAV39",
             "TRAV40",
             "TRAV41"]

tcr_dict_alpha = {"TRAV1-1": "CCTTAGTCGCTCTGATAGTTATGG",
                  "TRAV1-2-01": "CGAAGCACCCACATTTCTGTCTTA",
                  "TRAV1-2-02": "GTCGGTCTAAAGGGTACAGTTACC",
                  "TRAV2": "CAGGGACGATACAACATGACCTAT",
                  "TRAV3": "AACAAGAGCCAAACCTCCTTCC",
                  "TRAV4": "AGAAAGTCCAGCACTCTGAGCCT",
                  "TRAV5": "CGCATTGCAGACACCCAGACTG",
                  "TRAV6": "GGTCACCTTTGATACCACCCTTA",
                  "TRAV7": "ACAGCCGTGCAGCCTGAAGATTCA",
                  "TRAV8-1": "AGGAAACCCTCTGTGCAGTGG",
                  "TRAV8-2": "CATATGAGCGACGCGGCTGAGTAC",
                  "TRAV8-3": "GGAAACCCTCTGTGCATTGG",
                  "TRAV8-4": "TATGAGCGACGCGGCTGAGTA",
                  "TRAV8-5": "GACACTTATCACTTCCCCAATCAA",
                  "TRAV8-6": "ACCCTCAGTCCATATAAGCGACAC",
                  "TRAV8-7": "AAGAAGAGCGAAACCTCCTTCTA",
                  "TRAV9-1": "GAAGCCATGTACCGTAAAGAAAC",
                  "TRAV9-2": "TTGGAGAAAGGCTCAGTTCAAG",
                  "TRAV10": "AGCCTCCCAGCTCAGCGATTCA",
                  "TRAV11": "GTTTGGAATATCGCAGCCTCTCA",
                  "TRAV12-1": "GAGACTCCAAGCTCAGTGATTC",
                  "TRAV12-2": "GACTCCCAGCCCAGTGATTC",
                  "TRAV12-3": "AGGTTTACAGCACAGGTCGATAA",
                  "TRAV13-1": "CAAACATTTCTCCCTGcACATC",
                  "TRAV13-2": "CAGTGAAACATCTCTCTCTGCAAAT",
                  "TRAV14": "ATCCGCCAACCTTGTCATCT",
                  "TRAV15": "GGTCTCTCATCCTGGAGATTCA",
                  "TRAV16": "GAGACATCTTTCCACCTGAAGAA",
                  "TRAV17": "TCCAAGAAAAGCAGTTCCTTGTTG",
                  "TRAV18": "AGAGGTTTTCAGGCCAGTCCTAT",
                  "TRAV19": "ACAAGTCGTGGACTCAGCAGTATA",
                  "TRAV20": "TGCACATCACAGCCCCTAA",
                  "TRAV21": "ATGCCTCGCTGGATAAATCATCAG",
                  "TRAV22": "CTCTTCCCAGACCACAGACTC",
                  "TRAV23": "GCCAAGCAGTTCTCATTGCATATC",
                  "TRAV24": "ACCAAGGAGGGTTACAGCTATTTG",
                  "TRAV25": "CACATCACAGCCACCCAGACTAC",
                  "TRAV26-1": "GACAGAAAGTCCAGCACCTTGATC",
                  "TRAV26-2": "TcTCTGGCAATCGCTGAAGAC",
                  "TRAV27": "AAGGACAGTTCTCTCCACATCAC",
                  "TRAV28": "ACTTTATGGCCACCTATACATCAG",
                  "TRAV29": "CAGCCTGGAGACTCTGCAGTGTACT",
                  "TRAV30": "caGCAAAGCTCCCTGTACCT",
                  "TRAV31": "CACAGCCAGAAGACCTGCAACAT",
                  "TRAV32": "AACATGTCTCCCTGCATATTACAG",
                  "TRAV33": "TTCATCAACCTCACCATCAATTCC",
                  "TRAV34": "CAGCAAAGTTCCCTGCATATCAC",
                  "TRAV35": "ATAACCAGAAAGGACAGCTTCC",
                  "TRAV36": "ATCACAGCCACCCAGACCGGAGACT",
                  "TRAV37": "AGATTCACAGCCAGGCTTAAAA",
                  "TRAV38-1": "TTCCAGAAAGCAGCCAAATCC",
                  "TRAV38-2": "CTTCCAGAAAGCAGCCAAATCC",
                  "TRAV39": "CTCAGCACCCTCCACATCAC",
                  "TRAV40": "CAAAAACTTCGGAGGCGGAAATAT",
                  "TRAV41": "AAAGCACAGCTCCCTGCACATCAC"}

tcr_dict_beta = {"TRBV2": "TCAAATTTCACTCTGAAGATCCGGTCCACAA",
                 "TRBV3-1": "GCTCACTTAAATCTTCACATCAATTCCCTGG",
                 "TRBV4-1": "CTTAAACCTTCACCTACACGCCCTGC",
                 "TRBV4-2/3": "CTTATTCCTTCACCTACACACCCTGC",
                 "TRBV5-1": "GCTCTGAGATGAATGTGAGCACCTTG",
                 "TRBV5-3": "GCTCTGAGATGAATGTGAGTGCCTTG",
                 "TRBV5-4/5/6/7/8": "GCTCTGAGCTGAATGTGAACGCCTTG",
                 "TRBV6-1": "TCGCTCAGGCTGGAGTCGGCTG",
                 "TRBV6-2/3": "GCTGGGGTTGGAGTCGGCTG",
                 "TRBV6-4": "CCCTCACGTTGGCGTCTGCTG",
                 "TRBV6-5": "GCTCAGGCTGCTGTCGGCTG",
                 "TRBV6-6": "CGCTCAGGCTGGAGTTGGCTG",
                 "TRBV6-7": "CCCCTCAAGCTGGAGTCAGCTG",
                 "TRBV6-8": "CACTCAGGCTGGTGTCGGCTG",
                 "TRBV6-9": "CGCTCAGGCTGGAGTCAGCTG",
                 "TRBV7-1": "CCACTCTGAAGTTCCAGCGCACAC",
                 "TRBV7-2": "CACTCTGACGATCCAGCGCACAC",
                 "TRBV7-3": "CTCTACTCTGAAGATCCAGCGCACAG",
                 "TRBV7-4": "CCACTCTGAAGATCCAGCGCACAG",
                 "TRBV7-6": "CACTCTGACGATCCAGCGCACAG",
                 "TRBV7-7": "CCACTCTGACGATTCAGCGCACAG",
                 "TRBV7-8": "CCACTCTGAAGATCCAGCGCACAC",
                 "TRBV7-9": "CACCTTGGAGATCCAGCGCACAG",
                 "TRBV9": "GCACTCTGAACTAAACCTGAGCTCTCTG",
                 "TRBV10-1": "CCCCTCACTCTGGAGTCTGCTG",
                 "TRBV10-2": "CCCCCTCACTCTGGAGTCAGCTA",
                 "TRBV10-3": "CCTCCTCACTCTGGAGTCCGCTA",
                 "TRBV11-1/3": "CCACTCTCAAGATCCAGCCTGCAG",
                 "TRBV11-2": "CTCCACTCTCAAGATCCAGCCTGCAA",
                 "TRBV12-3/4/5": "CCACTCTGAAGATCCAGCCCTCAG",
                 "TRBV13": "CATTCTGAACTGAACATGAGCTCCTTGG",
                 "TRBV14": "CTACTCTGAAGGTGCAGCCTGCAG",
                 "TRBV15": "GATAACTTCCAATCCAGGAGGCCGAACA",
                 "TRBV16": "CTGTAGCCTTGAGATCCAGGCTACGA",
                 "TRBV17": "CTTCCACGCTGAAGATCCATCCCG",
                 "TRBV18": "GCATCCTGAGGATCCAGCAGGTAG",
                 "TRBV19": "CCTCTCACTGTGACATCGGCCC",
                 "TRBV20-1": "CTTGTCCACTCTGACAGTGACCAGTG",
                 "TRBV23-1": "CAGCCTGGCAATCCTGTCCTCAG",
                 "TRBV24-1": "CTCCCTGTCCCTAGAGTCTGCCAT",
                 "TRBV25-1": "CCCTGACCCTGGAGTCTGCCA",
                 "TRBV27": "CCCTGATCCTGGAGTCGCCCA",
                 "TRBV28": "CTCCCTGATTCTGGAGTCCGCCA",
                 "TRBV29-1": "CTAACATTCTCAACTCTGACTGTGAGCAACA ",
                 "TRBV30": "CGGCAGTTCATCCTGAGTTCTAAGAAGC"}

tcr_beta = ["TRBV2",
            "TRBV3-1",
            "TRBV4-1",
            "TRBV4-2/3",
            "TRBV5-1",
            "TRBV5-3",
            "TRBV5-4/5/6/7/8",
            "TRBV6-1",
            "TRBV6-2/3",
            "TRBV6-4",
            "TRBV6-5",
            "TRBV6-6",
            "TRBV6-7",
            "TRBV6-8",
            "TRBV6-9",
            "TRBV7-1",
            "TRBV7-2",
            "TRBV7-3",
            "TRBV7-4",
            "TRBV7-6",
            "TRBV7-7",
            "TRBV7-8",
            "TRBV7-9",
            "TRBV9",
            "TRBV10-1",
            "TRBV10-2",
            "TRBV10-3",
            "TRBV11-1/3",
            "TRBV11-2",
            "TRBV12-3/4/5",
            "TRBV13",
            "TRBV14",
            "TRBV15",
            "TRBV16",
            "TRBV17",
            "TRBV18",
            "TRBV19",
            "TRBV20-1",
            "TRBV23-1",
            "TRBV24-1",
            "TRBV25-1",
            "TRBV27",
            "TRBV28",
            "TRBV29-1",
            "TRBV30"]
