output_folder: results/ClustEval-2nd
input_objects:
  - results/ObjectCache/QualityControl/obj_strained_0DPI-MOCK-1_*.rds
  - results/ObjectCache/QualityControl/obj_strained_0DPI-MOCK-2_*.rds
  - results/ObjectCache/QualityControl/obj_strained_1DPI-MOCK-1_*.rds
  - results/ObjectCache/QualityControl/obj_strained_1DPI-MOCK-2_*.rds
  - results/ObjectCache/QualityControl/obj_strained_2DPI-MOCK-1_*.rds
  - results/ObjectCache/QualityControl/obj_strained_2DPI-MOCK-2_*.rds
  - results/ObjectCache/QualityControl/obj_strained_3DPI-MOCK-1_*.rds
  - results/ObjectCache/QualityControl/obj_strained_3DPI-MOCK-2_*.rds

subsample_rate: 0.8
num_of_subsample: 100

subsample_ks: "20 40 60 80 100 120 140"
subsample_resolutions: "0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8"
subsample_pcs: "10 15 20 25 30"
