---
title: "Analysis of Mock Samples"
author: "Altair Wei"
date: '2022-08-19'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("../scripts/EnrichmentUtilities.R")
source("../scripts/TrajectoryUtilities.R")
library(ggplot2)
```

## 加载数据

```{r}
obj <- readRDS(Sys.glob("../results/ObjectCache/IntegrationAndAnnotation/obj_annotated_*.rds"))
obj_mock <- subset(obj, subset = treatment == "MOCK")
```

```{r fig.height=9, fig.width=12}
ident_cols <- Seurat::DiscretePalette(length(levels(Seurat::Idents(obj))), palette = NULL)
df_to_plot <- SeuratObject::FetchData(obj, vars = c("ident", "tSNE_1", "tSNE_2", "time", "treatment"))
ggplot2::ggplot(df_to_plot, ggplot2::aes(x = tSNE_1, y = tSNE_2, color = ident)) +
  ggplot2::geom_point(size = 0.1) +
  ggplot2::facet_grid(treatment ~ time) +
  ggplot2::scale_color_manual(values = ident_cols) +
  ggplot2::coord_fixed() +
  ggplot2::guides(color = ggplot2::guide_legend(
    override.aes = list(size = 3), title = "Cell Type")) +
  cowplot::theme_cowplot()
```

```{r}
rm(obj)
gc()
```


## 细胞类型划分 {.tabset}

### t-SNE

```{r fig.height=8, fig.width=16}
p1 <- Seurat::DimPlot(
        obj_mock, reduction = "tsne", cols = ident_cols,
        label = TRUE, label.box = TRUE, label.color = "black", label.size = 2) +
  ggplot2::scale_fill_manual(values = rep("white", length(ident_cols))) +
  ggplot2::coord_fixed()
p2 <- Seurat::DimPlot(obj_mock, reduction = "tsne", group.by = "sample") +
  ggplot2::coord_fixed()
p1 + p2
```

### UMAP

```{r fig.height=8, fig.width=16}
p1 <- Seurat::DimPlot(
        obj_mock, reduction = "umap", cols = ident_cols,
        label = TRUE, label.box = TRUE, label.color = "black", label.size = 2) +
  ggplot2::scale_fill_manual(values = rep("white", length(ident_cols))) +
  ggplot2::coord_fixed()
p2 <- Seurat::DimPlot(obj_mock, reduction = "umap", group.by = "sample") +
  ggplot2::coord_fixed()
p1 + p2
```

## 特征基因功能分析

```{r message=FALSE, warning=FALSE, results="hide"}
library(org.Taestivum.iwgsc.db)
orgdb <- org.Taestivum.iwgsc.db
background <- rownames(Seurat::GetAssayData(obj_mock, assay = "RNA", slot = "count"))
```

```{r}
markerlist <- COSG::cosg(
 obj_mock,
 groups = 'all',
 assay = 'RNA',
 slot = 'data',
 mu = 1,
 n_genes_user = 300
)

markerlist <- markerlist$names
```

```{r include=FALSE}
# setup reactable HTML dependencies
reactable::reactable(iris)
```

### 维管束

```{r}
vascular_clusters <- c(paste0("Va_", 1:7), "MPV_1", "MPV_2", "BS", "CC")
```

#### 富集分析

```{r}
enr <- performMarkerCompareORA(
  markerlist,
  vascular_clusters,
  background
)
```

```{r fig.height=14, fig.width=12, message=FALSE, warning=FALSE}
p <- enr %>%
  enrichplot::pairwise_termsim() %>%
  enrichplot::treeplot(
    showCategory = 40, nCluster = 12,
    size = "count",
    offset = 70, offset_tiplab = 33,
    label_format_cladelab = 5,
    geneClusterPanel = "dotplot", nWords = 0) +
  ggplot2::scale_y_continuous(expand = ggplot2::expansion(mult = 0, add = 2)) +
  ggplot2::coord_cartesian()
p
```

#### 标志基因表格 {.tabset}

```{r results='asis'}
printCompareORAByCluster(enr, "#####")
```

### 其余细胞类型

```{r}
mesophyll_clusters <- c(paste0("Me_", 1:3), "Ep_1", "Ep_2", "Gu")
```

#### 富集分析

```{r}
enr <- performMarkerCompareORA(
  markerlist,
  mesophyll_clusters,
  background
)
```

```{r fig.height=16, fig.width=12, message=FALSE, warning=FALSE}
p <- enr %>%
  enrichplot::pairwise_termsim() %>%
  enrichplot::treeplot(
    showCategory = 40, nCluster = 12,
    size = "count",
    offset = 40, offset_tiplab = 20,
    label_format_cladelab = 5,
    geneClusterPanel = "dotplot", cex_category = 6, nWords = 0) +
  ggplot2::scale_y_continuous(expand = ggplot2::expansion(mult = 0, add = 2)) +
  ggplot2::coord_cartesian()
p
```

#### 标志基因表格 {.tabset}

```{r results='asis'}
printCompareORAByCluster(enr, "#####")
```
