---
title: "Arabidopsis thaliana shoots"
author: "Altair Wei"
date: "2022/1/20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1 构建 Seurat 对象

加载原始数据：

```{r}
shoots_counts <- readRDS("../tmp/shoots_counts.Rds")
shoots_meta <- readRDS("../tmp/shoots_meta.Rds")
names(shoots_meta) <- c("sample", "orig.cluster")
```

构建对象：

```{r}
obj <- Seurat::CreateSeuratObject(
  counts = shoots_counts,
  project = "Arabidopsis_thaliana_shoots",
  meta.data = shoots_meta
)
```

## 2 数据整合

### 2.1 数据预处理

```{r}
obj.list <- Seurat::SplitObject(obj, split.by = "sample")

obj.list <- lapply(X = obj.list, FUN = function(x) {
    x <- Seurat::NormalizeData(x)
    x <- Seurat::FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})

features <- Seurat::SelectIntegrationFeatures(object.list = obj.list)
```

### 2.2 开始整合

```{r}
anchors <- Seurat::FindIntegrationAnchors(object.list = obj.list, anchor.features = features)
```

```{r}
obj.combined <- Seurat::IntegrateData(anchorset = anchors)
```

## 3 整合数据的分析

### 3.1 移除生物协变量

#### 细胞周期效应

拟南芥基因细胞周期相关基因列表：

> Gutierrez, C. (2009). The Arabidopsis Cell Division Cycle. The Arabidopsis Book, 2009(7). https://doi.org/10.1199/tab.0120

```{r}
cell_cycle_genes_df <- tibble::tribble(
  ~Symbol,      ~ID,

  "CDKA;1",     "AT3G48750",
  "CDKB1;1",    "AT3G54180",
  "CDKB1;2",    "AT2G38620",
  "CDKB2;1",    "AT1G76540",
  "CDKB2;2",    "AT1G20930",
  "CDKC;1",     "AT5G10270",
  "CDKC;2",     "AT5G64960",
  "CDKD;1",     "AT1G73690",
  "CDKD;2",     "AT1G66750",
  "CDKD;3",     "AT1G18040",
  "CDKE;1",     "AT5G63610",
  "CDKF;1",     "AT4G28980",

  "CYCA1;1",    "AT1G44110",
  "CYCA1;2",    "AT1G77390",
  "CYCA2;1",    "AT5G25380",
  "CYCA2;2",    "AT5G11300",
  "CYCA2;3",    "AT1G15570",
  "CYCA2;4",    "AT1G80370",
  "CYCA3;1",    "AT5G43080",
  "CYCA3;2",    "AT1G47210",
  "CYCA3;3",    "AT1G47220",
  "CYCA3;4",    "AT1G47230",

  "CYCB1;1",    "AT4G37490",
  "CYCB1;2",    "AT5G06150",
  "CYCB1;3",    "AT3G11520",
  "CYCB1;4",    "AT2G26760",
  "CYCB2;1",    "AT2G17620",
  "CYCB2;2",    "AT4G35620",
  "CYCB2;3",    "AT1G20610",
  "CYCB2;4",    "AT1G76310",
  "CYCB3;1",    "AT1G16330",

  "CYCD1;1",    "AT1G70210",
  "CYCD2;1",    "AT2G22490",
  "CYCD3;1",    "AT4G34160",
  "CYCD3;2",    "AT5G67260",
  "CYCD3;3",    "AT3G50070",
  "CYCD4;1",    "AT5G65420",
  "CYCD4;2",    "AT5G10440",
  "CYCD5;1",    "AT4G37630",
  "CYCD6;1",    "AT4G03270",
  "CYCD7;1",    "AT5G02110",

  "CYCH;1",     "AT5G27620",

  "ICK1/KRP1",  "AT2G23430",
  "ICK2/KRP2",  "AT3G50630",
  "KRP3",       "AT5G48820",
  "KRP4",       "AT2G32710",
  "KRP5",       "AT3G24810",
  "KRP6",       "AT3G19150",
  "KRP7",       "AT1G49620",
  "SIM",        "AT5G04470",
  "CKS1",       "AT2G27960",
  "CKS2",       "AT2G27970",

  "RBR",        "AT3G12280",
  "E2FA",       "AT2G36010",
  "E2FB",       "AT5G22220",
  "E2FC",       "AT1G47870",
  "E2FD/DEL2",  "AT5G14960",
  "E2FE/DEL1",  "AT3G48160",
  "E2FF/DEL3",  "AT3G01330",
  "DPA",        "AT5G02470",
  "DPB",        "AT5G03415",

  "ORC1A",      "AT4G14700",
  "ORC1B",      "AT4G12620",
  "ORC2",       "AT2G37560",
  "ORC3",       "AT5G16690",
  "ORC4",       "AT2G01120",
  "ORC5",       "AT4G29910",
  "ORC6",       "AT1G26840",
  "CDC6A",      "AT2G29680",
  "CDC6B",      "AT1G07270",
  "CDT1A",      "AT2G31270",
  "CDT1B",      "AT3G54710",
  "GEM",        "AT2G22475",
  "PCNA1",      "AT1G07370",
  "PCNA2",      "AT2G29570",
  "FAS1",       "AT1G65470",
  "FAS2",       "AT5G64630",
  "MSI1",       "AT5G58230",

  "WEE1",       "AT1G02970",

  "KNOLLE",     "AT1G08560",
  "HINKEL",     "AT1G18370",

  "CCS52A1",    "AT4G22910",
  "CCS52A2",    "AT4G11920",
  "CCS52B",     "AT5G13840",

  "AUR1",       "AT4G32830",
  "AUR2",       "AT2G25880",
  "AUR3",       "AT2G45490",
  "TSL",        "AT5G20930"
)
```

#### 原生质体化效应

拟南芥原生质体化相关基因列表：

> Yadav, R. K., Girke, T., Pasala, S., Xie, M., & Reddy, G. V. (2009). Gene expression map of the Arabidopsis shoot apical meristem stem cell niche. Proceedings of the National Academy of Sciences, 106(12), 4941–4946. https://doi.org/10.1073/pnas.0900843106

```{r}
protoplasting_genes <- c(
  "ATMG00650", "ATMG00690", "ATMG01000", "ATMG01020", "ATMG00630", "ATCG01090", "ATCG01100", "ATMG00070", "ATMG00160", "ATCG01020",
  "ATCG00570", "ATCG00580", "ATCG00720", "ATCG00760", "ATCG00770", "ATCG00800", "ATCG00810", "ATCG00820", "ATCG00160", "ATCG00170",
  "ATCG00360", "ATCG00420", "ATCG00480", "ATCG00500", "ATCG00510", "ATCG00520", "ATCG00530", "ATCG00540", "ATCG00550", "ATCG00560",
  "ATCG00120", "ATCG00050", "AT1G67750", "AT4G15210", "AT4G14800", "AT4G14010", "AT4G15110", "AT4G14440", "AT1G25275", "AT5G04310",
  "AT1G73370", "AT1G44100", "AT1G73540", "AT5G09440", "AT5G09220", "AT5G20740", "AT5G10695", "AT5G08370", "AT5G08380", "AT4G36990",
  "AT4G36710", "AT4G36740", "AT3G51895", "AT5G15460", "AT5G15100", "AT1G31770", "AT5G29000", "AT5G27150", "AT5G25610", "AT5G24800",
  "AT5G65700", "AT5G65730", "AT5G65685", "AT5G64240", "AT5G63850", "AT5G62680", "AT5G60910", "AT5G60600", "AT5G57350", "AT5G57130",
  "AT5G55860", "AT5G55340", "AT5G55550", "AT5G55330", "AT5G54060", "AT5G53940", "AT5G52640", "AT5G50330", "AT5G48570", "AT5G47620",
  "AT5G47370", "AT5G45940", "AT5G45480", "AT5G45650", "AT5G44680", "AT5G43920", "AT5G43380", "AT5G43060", "AT5G42720", "AT5G39050",
  "AT5G37670", "AT5G35670", "AT5G23530", "AT5G18660", "AT5G18240", "AT5G16530", "AT5G13390", "AT5G10320", "AT5G09970", "AT5G07030",
  "AT5G04790", "AT5G04080", "AT5G04530", "AT5G03530", "AT5G02490", "AT5G02140", "AT5G02190", "AT3G63140", "AT2G45470", "AT3G57810",
  "AT3G57040", "AT3G56620", "AT3G55920", "AT3G55110", "AT3G52890", "AT3G51670", "AT3G51600", "AT3G43720", "AT4G39510", "AT4G38980",
  "AT4G36220", "AT4G34980", "AT4G33220", "AT4G32880", "AT4G32605", "AT4G30450", "AT4G29780", "AT4G29330", "AT4G29020", "AT4G28460",
  "AT4G28050", "AT4G27657", "AT4G25960", "AT4G25830", "AT4G24450", "AT4G23990", "AT4G22490", "AT4G21960", "AT4G21860", "AT4G21940",
  "AT4G21310", "AT4G21470", "AT4G20270", "AT4G18780", "AT4G12410", "AT4G11280", "AT4G10060", "AT4G05020", "AT4G04340", "AT4G03960",
  "AT4G02370", "AT4G02610", "AT4G02120", "AT4G01897", "AT4G00880", "AT2G33480", "AT1G19210", "AT3G12610", "AT3G12580", "AT3G06170",
  "AT1G75280", "AT1G66200", "AT3G21420", "AT3G23870", "AT3G13480", "AT3G15260", "AT3G12890", "AT3G26520", "ATMG01130", "ATMG01200",
  "ATMG01210", "ATMG01220", "ATMG01360", "ATMG01370", "ATMG00060", "AT1G78110", "AT3G13226", "AT3G12730", "AT3G12750", "AT3G18490",
  "AT3G18710", "AT3G13030", "AT3G19820", "AT3G25570", "AT3G20820", "AT3G24500", "AT3G21600", "AT3G16050", "AT3G14240", "AT3G14310",
  "AT3G06510", "AT3G06770", "AT3G04290", "AT3G09870", "AT3G07090", "AT3G09350", "AT3G01670", "AT3G07690", "AT3G03770", "AT3G16340",
  "AT1G17745", "AT1G55260", "AT1G67870", "AT1G67865", "AT1G73700", "AT1G73630", "AT1G71880", "AT1G63650", "AT1G74310", "AT1G68530",
  "AT1G69690", "AT1G69870", "AT1G68170", "AT1G68160", "AT1G11080", "AT1G11000", "AT2G43535", "AT1G78320", "AT1G21480", "AT1G53540",
  "AT1G07410", "AT1G75390", "AT1G20070", "AT1G05850", "AT1G35720", "AT1G53070", "AT1G14440", "AT1G71695", "AT1G30530", "AT1G08310",
  "AT1G15960", "AT1G80800", "AT1G22550", "AT1G79950", "AT1G77920", "AT1G78060", "AT1G68740", "AT1G27620", "AT1G73040", "AT1G72940",
  "AT1G17100", "AT1G14200", "AT1G75900", "AT1G28710", "AT1G11730", "AT1G11600", "AT1G14720", "AT1G64710", "AT1G64970", "AT1G75710",
  "AT1G24070", "AT1G23360", "AT1G78490", "AT1G54050", "AT1G54040", "AT2G38800", "AT2G15310", "AT2G20560", "AT2G22170", "AT2G21590",
  "AT2G36350", "AT2G21195", "AT2G21050", "AT2G03750", "AT1G02205", "AT1G65270", "AT1G54730", "AT1G22710", "AT1G04220", "AT2G17640",
  "AT1G23090", "AT1G62570", "AT2G07705", "AT2G16700", "AT2G16720", "AT2G10940", "AT2G46590", "AT2G05520", "AT2G32120", "AT2G17975",
  "AT2G01670", "AT2G25680", "AT2G07680", "AT2G07728", "AT2G18660", "AT2G37900", "AT2G27820", "AT2G26990", "AT2G46630", "AT2G46240",
  "AT2G46800", "AT2G26150", "AT2G26810", "AT2G30890", "AT2G39890", "AT2G44420", "AT2G26250", "AT2G26170", "AT2G34810", "AT2G32690"
)
```

#### 移除协变量

```{r}
Seurat::DefaultAssay(obj.combined) <- "integrated"

vars_regress <- unique(c(cell_cycle_genes_df$ID, protoplasting_genes))

obj.combined <- Seurat::ScaleData(
  obj.combined,
  vars.to.regress = vars_regress,
  verbose = FALSE
)
```

### 3.2 维度缩减

```{r}
Seurat::Idents(obj.combined) <- "orig.cluster"
```

```{r}
Seurat::DefaultAssay(obj.combined) <- "RNA"

markers_df <- tibble::tribble(
  ~Name,          ~ID,
  "FBA5",       "AT4G26530",
  "ESM1",       "AT3G14210",
  "CRR23",      "AT1G70760",
  "ATBCB",      "AT5G20230",
  "AOC2",       "AT3G25770",
  "AR781",      "AT2G26530",
  "STM",        "AT1G62360",
  "KNAT1",      "AT4G08150",
  "CYP78A5",    "AT1G13710",
  "LSH3",       "AT2G31160",
  "AST68",      "AT5G10180",
  "GDU4",       "AT2G24762",
  "NIP6",       "AT1G80760",
  "TED4",       "AT3G18280",
  "bHLH112",    "AT1G61660",
  "SULTR3;4",   "AT3G15990",
  "PHO1",       "AT3G23430",
  "FST",        "AT1G64625",
  "PIN6",       "AT1G77110",
  "LAX2",       "AT2G21050",
  "FLA12",      "AT5G60490",
  "AACT1",      "AT5G47720",
  "FAF3",       "AT5G19260",
  "OBP2",       "AT1G07640",
  "CLE25",      "AT3G28455",
  "SMXL5",      "AT5G57130",
  "ATGSL07",    "AT1G06490",
  "DOF5.6",     "AT5G62940",
  "GATA19",     "AT4G36620",
  "ACI1",       "AT5G01370",
  "RUL1",       "AT5G05160",
  "ATCSLD5",    "AT1G02730",
  "ATSYP111",   "AT1G08560",
  "3xHMG−box2", "AT4G23800",
  "PDF1",       "AT2G42840",
  "FDH",        "AT2G26250",
  "ATML1",      "AT4G21750",
  "EDA17",      "AT1G72970",
  "BDG1",       "AT1G64670",
  "DCR",        "AT5G23940",
  "POLAR",      "AT4G31805",
  "BASL",       "AT5G60880",
  "SPCH",       "AT5G53210",
  "FAMA",       "AT3G24140",
  "ATEPF1",     "AT2G20875",
  "MYB60",      "AT1G08810",
  "ALMT12",     "AT4G17970",
  "SCAP1",      "AT5G65590",
  "AN5",        "AT4G19840",
  "SUC2",       "AT1G22710",
  "ATC",        "AT1G47960",
  "EFM",        "AT2G03500",
  "TET6",       "AT3G12090",
  "NAKR1",      "AT5G02600",
  "CEPR1",      "AT5G49660",
  "CDEF1",      "AT4G30140"
)
```

```{r fig.height=8, fig.width=8}
Seurat::DotPlot(
  obj.combined,
  features = rev(markers_df$ID),
  cluster.idents = FALSE
) +
  ggplot2::scale_x_discrete(labels = rev(markers_df$Name)) +
  ggplot2::scale_y_discrete(limits = c(
    "4", "0", "3", "16",
    "20",
    "13", "1",
    "6", "10", "7", "22",
    "19", "5", "17", "9",
    "8",
    "2", "14", "12", "18",
    "11", "15", "21"
  )) +
  ggplot2::coord_flip()
```

```{r}
saveRDS(obj.combined, "../tmp/shoots_obj.rds")
```

