---
title: "Compositional Analysis by scCODA"
author: "Altair Wei"
date: '2022-07-20'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("../scripts/LoadUtils.R", chdir = TRUE)
```

## Prepare Data

```{r}
obj <- readRDS(Sys.glob("../results/ObjectCache/IntegrationAndAnnotation/obj_annotated_*.rds"))
```

### Cell Annotation

```{r}
all_celltypes <- c(
  "Gu", "Ep_1", "Ep_2",
  "Me_1", "Me_2", "Me_3", "Me_4", "Me_5", "Me_6",
  "Va_1", "Va_2", "Va_3", "Va_4",
  "BS", "CC", "MPV_1", "MPV_2")

all_celltype_colors <- ggthemes::tableau_color_pal("Tableau 20")(length(all_celltypes))
names(all_celltype_colors) <- all_celltypes
```

```{r}
all_body_layers <- c(
  "Gu"    = "L1",
  "Ep_1"  = "L1",
  "Ep_2"  = "L1",
  "Me_1"  = "L2",
  "Me_2"  = "L2",
  "Me_3"  = "L2",
  "Me_4"  = "L2",
  "Me_5"  = "L2",
  "Me_6"  = "L2",
  "Va_1"  = "L2",
  "Va_2"  = "L2",
  "Va_3"  = "L2",
  "Va_4"  = "L2",
  "BS"    = "L3",
  "CC"    = "L3",
  "MPV_1" = "L3",
  "MPV_2" = "L3"
)

all_tissues <- c(
  Gu   = "Stomata",
  Ep_1 = "Epidermis",
  Ep_2 = "Epidermis",
  Me_1 = "Chlorenchyma",
  Me_2 = "Chlorenchyma",
  Me_3 = "Chlorenchyma",
  Me_4 = "Parenchyma",
  Me_5 = "Parenchyma",
  Me_6 = "Parenchyma",
  Va_1 = "Chlorenchyma",
  Va_2 = "Outer sheath",
  Va_3 = "Outer sheath",
  Va_4 = "Outer sheath",
  BS = "Inner sheath",
  CC = "Phloem",
  MPV_1 = "Procambium",
  MPV_2 = "Procambium"
)
```

```{r}
Seurat::Idents(obj) <- forcats::fct_relevel(Seurat::Idents(obj), all_celltypes)
obj$body_layer <- do.call(
  dplyr::recode, c(list(.x = Seurat::Idents(obj)), as.list(all_body_layers)))
obj$tissue <- do.call(
  dplyr::recode, c(list(.x = Seurat::Idents(obj)), as.list(all_tissues)))
```

### Cell Population Size

计算细胞类型大小：

```{r}
df <- rhapsodykit::calculateClusterSize(
    Seurat::Idents(obj), obj$sample, obj$group)
df$time <- stringr::str_extract(df$sample_id, "\\dDPI")
df$treatment <- stringr::str_extract(df$sample_id, "MOCK|PNR2|TR4")
df <- tidyr::pivot_wider(df, names_from = cluster_id, values_from = size)

reactable::reactable(df)
```

```{r}
dftis <- rhapsodykit::calculateClusterSize(obj$tissue, obj$sample, obj$group)
dftis$time <- stringr::str_extract(dftis$sample_id, "\\dDPI")
dftis$treatment <- stringr::str_extract(dftis$sample_id, "MOCK|PNR2|TR4")
dftis <- tidyr::pivot_wider(dftis, names_from = cluster_id, values_from = size)

reactable::reactable(dftis)
```


### Functions

```{r}
runScCODA <- function(df, formula, ref, num_results = 20000L) {
  dat <- reticulate::import("sccoda.util.cell_composition_data")
  mod <- reticulate::import("sccoda.util.comp_ana")

  andata <- dat$from_pandas(df, covariate_columns = c(
    "sample_id", "group_id", "time", "treatment"))
  model <- mod$CompositionalAnalysis(
    andata, formula = formula, reference_cell_type = ref)
  sim <- model$sample_hmc(num_results = num_results)

  sim
}

summaryScCODA <- function(sim, ...) {
  summ <- sim$summary_prepare(...)

  list(
    intercepts = cbind(
      reticulate::py_to_r(
        attr(summ[[1]], "pandas.index")$to_frame()),
      summ[[1]]
    ),
    effects = cbind(
      reticulate::py_to_r(
        attr(summ[[2]], "pandas.index")$to_frame()),
      summ[[2]]
    )
  )
}

plotSummary <- function(summ) {
  ggplot2::ggplot(
      data = summ$effects,
      mapping = ggplot2::aes(
        x = .data[["Expected Sample"]],
        y = .data[["Final Parameter"]],
        color = .data[["Cell Type"]],
        size = abs(.data[["log2-fold change"]]))) +
    ggplot2::geom_point() +
    ggrepel::geom_text_repel(ggplot2::aes(label = .data[["Cell Type"]]),
                             size = 4, color = "black", bg.color = "white") +
    ggplot2::guides(color = ggplot2::guide_legend(ncol = 2)) +
    ggplot2::theme_bw()
}

printIntercepts <- function(intercepts) {
  reactable::reactable(
    data = intercepts,
    rownames = FALSE,
    columns = list(
      "Final Parameter" = reactable::colDef(
        format = reactable::colFormat(digits = 3)),
      "Expected Sample" = reactable::colDef(
        format = reactable::colFormat(digits = 1))
    )
  )
}

printEffects <- function(effects) {
  reactable::reactable(
    data = effects,
    rownames = FALSE,
    columns = list(
      "Final Parameter" = reactable::colDef(
        format = reactable::colFormat(digits = 3)),
      "Inclusion probability" = reactable::colDef(
        format = reactable::colFormat(digits = 3)),
      "Expected Sample" = reactable::colDef(
        format = reactable::colFormat(digits = 1)),
      "log2-fold change" = reactable::colDef(
        format = reactable::colFormat(digits = 3))
    )
  )
}
```

```{r}
FDR_LIM = 0.05
```

## Cell Clusters

### Time as the covariate

#### MOCK Analysis

```{r}
sim_mock <- cache_pickle(
  file = "sccoda_clusters_sim_mock.pickle",
  dir = "../results/ObjectCache/DifferentialAbundance/",
  expr = dplyr::filter(df, time == "0DPI" | treatment == "MOCK") |>
    dplyr::mutate(time = as.integer(substr(time, 1, 1))) |>
    runScCODA("time", "Gu")
)
```

```{r}
summ_mock <- summaryScCODA(sim_mock, est_fdr = FDR_LIM)
```

```{r}
summ_mock$intercepts |>
  printIntercepts()
```

```{r}
summ_mock$effects |>
  printEffects()
```

```{r}
plotSummary(summ_mock) +
  ggthemes::scale_color_tableau("Tableau 20")
```


#### PNR2 Analysis

```{r}
sim_pnr2 <- cache_pickle(
  file = "sccoda_clusters_sim_pnr2.pickle",
  dir = "../results/ObjectCache/DifferentialAbundance/",
  expr = dplyr::filter(df, time == "0DPI" | treatment == "PNR2") |>
      dplyr::mutate(time = as.integer(substr(time, 1, 1))) |>
      runScCODA("time", "Gu")
)
```

```{r}
summ_pnr2 <- summaryScCODA(sim_pnr2, est_fdr = FDR_LIM)
```

```{r}
summ_pnr2$intercepts |>
  printIntercepts()
```

```{r}
summ_pnr2$effects |>
  printEffects()
```

```{r}
plotSummary(summ_pnr2) +
  ggthemes::scale_color_tableau("Tableau 20")
```

#### TR4 Analysis

```{r}
sim_tr4 <- cache_pickle(
  file = "sccoda_clusters_sim_tr4.pickle",
  dir = "../results/ObjectCache/DifferentialAbundance/",
  expr = dplyr::filter(df, time == "0DPI" | treatment == "TR4") |>
      dplyr::mutate(time = as.integer(substr(time, 1, 1))) |>
      runScCODA("time", "Gu")
)
```

```{r}
summ_tr4 <- summaryScCODA(sim_tr4, est_fdr = FDR_LIM)
```

```{r}
summ_tr4$intercepts |>
  printIntercepts()
```

```{r}
summ_tr4$effects |>
  printEffects()
```

```{r}
plotSummary(summ_tr4) +
  ggthemes::scale_color_tableau("Tableau 20")
```

### Treatment as the covariate

#### 1DPI Analysis

```{r}
sim_1dpi <- cache_pickle(
  file = "sccoda_clusters_sim_1dpi.pickle",
  dir = "../results/ObjectCache/DifferentialAbundance/",
  expr = runScCODA(
    dplyr::filter(df, time == "1DPI"), "treatment", "Gu")
)
```

```{r}
summ_1dpi <- summaryScCODA(sim_1dpi)
```

```{r}
summ_1dpi$intercepts |>
  printIntercepts()
```

```{r}
summ_1dpi$effects |>
  printEffects()
```

#### 2DPI Analysis

```{r}
sim_2dpi <- cache_pickle(
  file = "sccoda_clusters_sim_2dpi.pickle",
  dir = "../results/ObjectCache/DifferentialAbundance/",
  expr = runScCODA(
    dplyr::filter(df, time == "2DPI"), "treatment", "Gu")
)
```

```{r}
summ_2dpi <- summaryScCODA(sim_2dpi)
```

```{r}
summ_2dpi$intercepts |>
  printIntercepts()
```

```{r}
summ_2dpi$effects |>
  printEffects()
```

#### 3DPI Analysis

```{r}
sim_3dpi <- cache_pickle(
  file = "sccoda_clusters_sim_3dpi.pickle",
  dir = "../results/ObjectCache/DifferentialAbundance/",
  expr = runScCODA(
    dplyr::filter(df, time == "3DPI"), "treatment", "Gu")
)
```

```{r}
summ_3dpi <- summaryScCODA(sim_3dpi)
```

```{r}
summ_3dpi$intercepts |>
  printIntercepts()
```

```{r}
summ_3dpi$effects |>
  printEffects()
```

## Cell Types

### Time as the covariate

#### MOCK Analysis

```{r}
tis_mock <- cache_pickle(
  file = "sccoda_celltypes_sim_mock.pickle",
  dir = "../results/ObjectCache/DifferentialAbundance/",
  expr = dplyr::filter(dftis, time == "0DPI" | treatment == "MOCK") |>
    dplyr::mutate(time = as.integer(substr(time, 1, 1))) |>
    runScCODA("time", "Stomata")
)
```

```{r}
summ_tis_mock <- summaryScCODA(tis_mock, est_fdr = FDR_LIM)
```

```{r}
summ_tis_mock$intercepts |>
  printIntercepts()
```

```{r}
summ_tis_mock$effects |>
  printEffects()
```

```{r}
summ_tis_mock$effects <- dplyr::mutate(
  summ_tis_mock$effects,
  `Cell Type` = factor(`Cell Type`, levels = unique(all_tissues)))

plotSummary(summ_tis_mock) +
  ggthemes::scale_color_tableau("Tableau 10")
```

#### PNR2 Analysis

```{r}
tis_pnr2 <- cache_pickle(
  file = "sccoda_celltypes_sim_pnr2.pickle",
  dir = "../results/ObjectCache/DifferentialAbundance/",
  expr = dplyr::filter(dftis, time == "0DPI" | treatment == "PNR2") |>
    dplyr::mutate(time = as.integer(substr(time, 1, 1))) |>
    runScCODA("time", "Stomata")
)
```

```{r}
summ_tis_pnr2 <- summaryScCODA(tis_pnr2, est_fdr = FDR_LIM)
```

```{r}
summ_tis_pnr2$intercepts |>
  printIntercepts()
```

```{r}
summ_tis_pnr2$effects |>
  printEffects()
```

```{r}
summ_tis_pnr2$effects <- dplyr::mutate(
  summ_tis_pnr2$effects,
  `Cell Type` = factor(`Cell Type`, levels = unique(all_tissues)))

plotSummary(summ_tis_pnr2) +
  ggthemes::scale_color_tableau("Tableau 10")
```

#### TR4 Analysis

```{r}
tis_tr4 <- cache_pickle(
  file = "sccoda_celltypes_sim_tr4.pickle",
  dir = "../results/ObjectCache/DifferentialAbundance/",
  expr = dplyr::filter(dftis, time == "0DPI" | treatment == "TR4") |>
    dplyr::mutate(time = as.integer(substr(time, 1, 1))) |>
    runScCODA("time", "Stomata")
)
```

```{r}
summ_tis_tr4 <- summaryScCODA(tis_tr4, est_fdr = FDR_LIM)
```

```{r}
summ_tis_tr4$intercepts |>
  printIntercepts()
```

```{r}
summ_tis_tr4$effects |>
  printEffects()
```

```{r}
summ_tis_tr4$effects <- dplyr::mutate(
  summ_tis_tr4$effects,
  `Cell Type` = factor(`Cell Type`, levels = unique(all_tissues)))

plotSummary(summ_tis_tr4) +
  ggthemes::scale_color_tableau("Tableau 10")
```
