---
title: "Deconvolution of LCM-seq data with CIBERSORTx"
author: "Altair Wei"
date: "2023-08-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("../scripts/LoadUtils.R", chdir = TRUE)
source("../secrets")
```

## Prepare Count Matrix

```{r}
obj_mock <- readRDS(Sys.glob(
  "../results/ObjectCache/IntegrationAndAnnotation/obj_mock_annotated_*.rds"))
```

### MOCK samples

```{r}
sce_mock <- Seurat::as.SingleCellExperiment(obj_mock, assay = "RNA")
sce_mock <- muscat::prepSCE(sce_mock,
  kid = "ident", # subpopulation assignments
  gid = "group", # group IDs (ctrl/stim)
  sid = "sample", # sample IDs (ctrl/stim.1234)
  drop = FALSE
)
```

```{r}
mock_celltypes <- c(
  "Gu", "Ep_α", "Ep_β",
  "Me_α", "Me_β", "Me_γ", "Me_δ", "Me_ε",
  "BS", "CC", "Va_α", "Va_β", "Va_γ", "Va_δ", "MPV")

mock_celltype_names <- c(
  "Guard cell", "Epidermal α", "Epidermal β",
  
  "Mesophyll α", "Mesophyll β", "Mesophyll γ",
  "Mesophyll δ", "Mesophyll ε",
  
  "Vascular bundle sheath", "Phloem companion cell",
  "Vascular α", "Vascular β", "Vascular γ",
  "Vascular δ", "Midvein provascular cell"
)

mock_celltype_colors <- ggthemes::tableau_color_pal("Tableau 20")(length(mock_celltypes))
#mock_celltype_colors <- scater:::.get_palette("tableau20")[seq_along(mock_celltypes)]
names(mock_celltype_colors) <- mock_celltypes
```

```{r}
mock_body_layers <- c(
  "Gu"   = "L1",
  "Ep_α" = "L1",
  "Ep_β" = "L1",
  "Me_α" = "L2",
  "Me_β" = "L2",
  "Me_γ" = "L2",
  "Me_δ" = "L2",
  "Me_ε" = "L2",
  "BS"   = "L3",
  "CC"   = "L3",
  "Va_α" = "L3",
  "Va_β" = "L3",
  "Va_γ" = "L3",
  "Va_δ" = "L3",
  "MPV"  = "L3"
)
```

```{r}
sce_mock$cluster_id <- forcats::fct_relevel(sce_mock$cluster_id, mock_celltypes)
sce_mock$body_layer <- do.call(
  dplyr::recode, c(list(.x = sce_mock$cluster_id), as.list(mock_body_layers)))
Seurat::Idents(obj_mock) <- forcats::fct_relevel(Seurat::Idents(obj_mock), mock_celltypes)
```

```{r}
sce_slim <- sce_mock
logcounts(sce_slim) <- NULL
sce_slim <- sce_slim[
  # Gene expressed in at least 10 cells
  Matrix::rowSums(counts(sce_slim) > 0) > 10,
  # Ensure no empty cell
  Matrix::colSums(counts(sce_slim)) > 0
]

mtx <- as.matrix(counts(sce_slim))
colnames(mtx) <- sce_slim$cluster_id
rownames(mtx) <- rownames(sce_slim)

# To save disk, because expression matrix has been corrected by SoupX
mtx <- round(mtx, digits = 1)
```

注意，不要缺失第一列的列名，否则会导致 cell labels 完全错位！这里使用自定义的 `writeMatrixToTSV` 函数修正了 `write.table` 的不足。

```{r}
writeMatrixToTSV(mtx, "../results/Deconv/sc_mock_counts.tsv")
```

### Optimal clustering

```{r}
npcs <- 20
k <- 40
res <- 0.3

obj_mock <- obj_mock %>%
    Seurat::FindNeighbors(reduction = "harmony", verbose = FALSE,
                          dims = seq_len(npcs), k.param = k) %>%
    Seurat::FindClusters(resolution = res, verbose = FALSE,random.seed = 230816)
```

```{r fig.height=7, fig.width=8}
Seurat::DimPlot(
        obj_mock, reduction = "umap",
        cols = Seurat::DiscretePalette(
          length(levels(Seurat::Idents(obj_mock))), palette = NULL),
        label = TRUE, label.box = TRUE, label.color = "black", label.size = 2) +
  ggplot2::scale_fill_manual(
    values = rep("white", length(levels(Seurat::Idents(obj_mock))))) +
  ggplot2::coord_fixed() +
  theme_dimred() +
  ggplot2::ggtitle(sprintf("pc=%s, k=%s, res=%s", npcs, k, res)) +
  center_plot_title()
```

```{r}
sce_mock <- Seurat::as.SingleCellExperiment(obj_mock, assay = "RNA")
sce_mock <- muscat::prepSCE(sce_mock,
  kid = "ident", # subpopulation assignments
  gid = "group", # group IDs (ctrl/stim)
  sid = "sample", # sample IDs (ctrl/stim.1234)
  drop = TRUE
)
```

```{r}
sce_slim <- sce_mock
logcounts(sce_slim) <- NULL
sce_slim <- sce_slim[
  # Gene expressed in at least 10 cells
  Matrix::rowSums(counts(sce_slim) > 0) > 10,
  # Ensure no empty cell
  Matrix::colSums(counts(sce_slim)) > 0
]

mtx <- as.matrix(counts(sce_slim))
colnames(mtx) <- sce_slim$cluster_id
rownames(mtx) <- rownames(sce_slim)

# To save disk, because expression matrix has been corrected by SoupX
mtx <- round(mtx, digits = 1)
```

```{r}
writeMatrixToTSV(mtx, "../results/Deconv-Optimum/sc_mock_counts.tsv")
```

## Build Signature Matrix

```{r}
rm(sce_mock, sce_slim, mtx)
gc()
```

### Create signature matrix

```{r}
build_sigmatrix <- function(folder) {
  ret <- system2(
    command = "docker",
    args = c(
      "run",
      "-v", sprintf("%s:/src/data", fs::path_abs(folder)), 
      "-v", sprintf("%s:/src/outdir", fs::path_abs(folder)),
      "cibersortx/fractions",
      "--username",    USERNAME,
      "--token",       TOKEN,
      "--single_cell", "TRUE",
      "--fraction",    "0",
      "--refsample",   "sc_mock_counts.tsv",
      "--verbose",      "TRUE"
    )
  )

  if (ret) {
    sigmatrix_file = sprintf("%s/CIBERSORTx_%s_inferred_phenoclasses.CIBERSORTx_%s_inferred_refsample.bm.K%s.txt",
                           folder, "sc_mock_counts", "sc_mock_counts", 999)
    file.rename(sigmatrix_file, sprintf("%s/%s_sigmatrix.tsv", folder, "sc_mock_counts"))
  } else {
    stop("Failed to build signature matrix.") 
  }
}
```

```{r}
build_sigmatrix("../results/Deconv/")
```

### Visualization of signature matrix

```{r}
sigmatrix <- readr::read_tsv("../results/Deconv/sc_mock_counts_sigmatrix.tsv") |>
  tibble::column_to_rownames("NAME") |>
  as.matrix()
```

```{r fig.height=8, fig.width=7}
heatmap(sigmatrix, col = colorRamps::blue2red(50), labRow=NA, ylab=NA)
```

```{r}
ComplexHeatmap::Heatmap(
  matrix = t(scale(t(sigmatrix))),
  col = viridis::viridis(256),
  show_row_names = FALSE,
  row_dend_width = grid::unit(30, "mm")
)
```


## Impute Cell Fractions

### Prepare LCM-seq TPM matrix

这个不是 TPM，需要自己合并一下。

```{r}
lcm_tpm_mtx <- getTpmMatrixLCM("../results/LCMSeq/gene_quanti/tpm")
writeMatrixToTSV(lcm_tpm_mtx, file = "../results/Deconv/lcm_tpm_matrix.tsv")
```

### Impute fractions

```{r}
system2(
  command = "docker",
  args = c(
    "run",
    "-v", sprintf("%s:/src/data", fs::path_abs("../results/Deconv/")), 
    "-v", sprintf("%s:/src/outdir", fs::path_abs("../results/Deconv/")),
    "cibersortx/fractions",
    "--username",     USERNAME,
    "--token",        TOKEN,
    "--refsample",    "sc_mock_counts.tsv",
    "--mixture",      "lcm_tpm_matrix.tsv",
    "--sigmatrix",    "sc_mock_counts_sigmatrix.tsv",
    "--perm",         "100",
    "--rmbatchSmode", "TRUE",
    "--verbose",      "TRUE"
  )
)
```

### Visualization of cell fractions

```{r}
CIBER_raw <- readr::read_tsv("../results/Deconv/CIBERSORTx_Adjusted.txt")
CIBER_extra <- dplyr::select(CIBER_raw, Sample = Mixture, `P-value`, Correlation, RMSE)
CIBER_frac <- dplyr::select(CIBER_raw, Sample = Mixture, !c(`P-value`, Correlation, RMSE)) |>
  tidyr::pivot_longer(!Sample, names_to = "CellType", values_to = "Fraction")
```

```{r}
LCM_design <- c(
  "VC_1" = "vb.",
  "VC_2" = "vb.",
  "VC_3" = "vb.",
  "CC_1" = "bp.",
  "CC_2" = "bp.",
  "CC_3" = "bp.",
  "MC3_1" = "dp.",
  "MC3_2" = "dp.",
  "MC3_3" = "dp.",
  "MC_1" = "me.",
  "MC_2" = "me.",
  "MC_3" = "me.",
  "EC_1" = "ep.",
  "EC_2" = "ep.",
  "EC_3" = "ep."
)

CIBER_frac$SampleClass <- dplyr::recode(CIBER_frac$Sample, !!!LCM_design)
CIBER_frac$CellType <- factor(CIBER_frac$CellType, levels = mock_celltypes)
```

```{r fig.height=7, fig.width=7}
p <- deconvScatter(CIBER_frac, LCM_design, ncol = 3, theme_size = 14) +
  ggplot2::theme(
    axis.text.x = ggplot2::element_text(angle = 0, hjust = 0.5, vjust = 0.5))

p
```

```{r fig.height=7, fig.width=5}
p <- deconvScatter(CIBER_frac, LCM_design, ncol = 3, theme_size = 14) +
  ggplot2::theme(
    axis.text.x = ggplot2::element_text(angle = 0, hjust = 0.5, vjust = 0.5),
    axis.text.y = ggplot2::element_blank(),
    axis.ticks.y = ggplot2::element_blank())

p
```

```{r}
deconvBarplot(CIBER_frac) +
  ggplot2::scale_fill_manual(values = mock_celltype_colors)
```

