---
title: "Slides for Paper Figures"
author: "Altair Wei"
date: "2023-08-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(magrittr)
library(ggtree, include.only = "%<+%")
source("../scripts/LoadUtils.R", chdir = TRUE)

options(ggrastr.default.dpi=300)
#ggplot2::theme_set(cowplot::theme_cowplot(font_size = 22, font_family = "Arial"))
PT = 1/2.13
FT = 6/17.1
```

## Load Data Objects

### Seurat Objects

#### MOCK samples

```{r}
obj_mock <- readRDS(Sys.glob("../results/ObjectCache/IntegrationAndAnnotation/obj_mock_annotated_*.rds"))
sce_mock <- Seurat::as.SingleCellExperiment(obj_mock, assay = "RNA")
sce_mock <- muscat::prepSCE(sce_mock,
  kid = "ident", # subpopulation assignments
  gid = "group", # group IDs (ctrl/stim)
  sid = "sample", # sample IDs (ctrl/stim.1234)
  drop = FALSE
)
```

```{r}
mock_celltypes <- c(
  "Gu", "Ep_α", "Ep_β",
  "Me_α", "Me_β", "Me_ε", "Me_γ", "Va_δ", "Me_δ",
  "Va_β", "BS", "CC", "MPV", "Va_α", "Va_γ")

mock_celltype_colors <- ggthemes::tableau_color_pal("Tableau 20")(length(mock_celltypes))
names(mock_celltype_colors) <- mock_celltypes
```

```{r}
mock_body_layers <- c(
  "Gu"   = "L1",
  "Ep_α" = "L1",
  "Ep_β" = "L1",
  "Me_α" = "L2",
  "Me_β" = "L2",
  "Me_γ" = "L2",
  "Me_δ" = "L2",
  "Me_ε" = "L2",
  "BS"   = "L3",
  "CC"   = "L3",
  "Va_α" = "L3",
  "Va_β" = "L3",
  "Va_γ" = "L3",
  "Va_δ" = "L3",
  "MPV"  = "L3"
)
```

```{r}
sce_mock$cluster_id <- forcats::fct_relevel(sce_mock$cluster_id, mock_celltypes)
sce_mock$body_layer <- do.call(
  dplyr::recode, c(list(.x = sce_mock$cluster_id), as.list(mock_body_layers)))
Seurat::Idents(obj_mock) <- forcats::fct_relevel(Seurat::Idents(obj_mock), mock_celltypes)
```

#### All samples

```{r}
obj <- readRDS(Sys.glob("../results/ObjectCache/IntegrationAndAnnotation/obj_annotated_*.rds"))
sce <- Seurat::as.SingleCellExperiment(obj, assay = "RNA")
sce <- muscat::prepSCE(sce,
  kid = "ident", # subpopulation assignments
  gid = "group", # group IDs (ctrl/stim)
  sid = "sample", # sample IDs (ctrl/stim.1234)
  drop = FALSE
)
```

```{r}
all_celltypes <- c(
   "Gu", "Ep_1", "Ep_2",
  "Me_1", "Me_2", "Me_3", "Me_4", "Me_5", "Me_6",
  "Va_1", "Va_2", "Va_3", "Va_4",
  "BS", "CC", "MPV_1", "MPV_2")

all_celltype_colors <- ggthemes::tableau_color_pal("Tableau 20")(length(all_celltypes))
#mock_celltype_colors <- scater:::.get_palette("tableau20")[seq_along(mock_celltypes)]
names(all_celltype_colors) <- all_celltypes
scales::show_col(all_celltype_colors)
```

```{r}
all_body_layers <- c(
  "Gu"    = "L1",
  "Ep_1"  = "L1",
  "Ep_2"  = "L1",
  "Me_1"  = "L2",
  "Me_2"  = "L2",
  "Me_3"  = "L2",
  "Me_4"  = "L2",
  "Me_5"  = "L2",
  "Me_6"  = "L2",
  "Va_1"  = "L2",
  "Va_2"  = "L2",
  "Va_3"  = "L2",
  "Va_4"  = "L2",
  "BS"    = "L3",
  "CC"    = "L3",
  "MPV_1" = "L3",
  "MPV_2" = "L3"
)

all_tissues <- c(
  Gu   = "Stomata",
  Ep_1 = "Epidermis",
  Ep_2 = "Epidermis",
  Me_1 = "Chlorenchyma",
  Me_2 = "Chlorenchyma",
  Me_3 = "Chlorenchyma",
  Me_4 = "Parenchyma",
  Me_5 = "Parenchyma",
  Me_6 = "Parenchyma",
  Va_1 = "Chlorenchyma",
  Va_2 = "Outer sheath",
  Va_3 = "Outer sheath",
  Va_4 = "Outer sheath",
  BS = "Inner sheath",
  CC = "Phloem",
  MPV_1 = "Procambium",
  MPV_2 = "Procambium"
)

all_tissues_colors <- structure(
  names = c("Stomata",      "Epidermis",    "Chlorenchyma", "Parenchyma",
            "Outer sheath", "Inner sheath", "Phloem",       "Procambium"),
  .Data = c("#4e79a7",      "#f28e2b",      "#8cd17d",      "#b6992d",
            "#86bcb6",      "#e15759",      "#ff9d9a",      "#79706e")
)


obj$tissue <- do.call(
  dplyr::recode, c(list(.x = Seurat::Idents(obj)), as.list(all_tissues)))
```

```{r}
sce$cluster_id <- forcats::fct_relevel(sce$cluster_id, all_celltypes)
Seurat::Idents(obj) <- forcats::fct_relevel(Seurat::Idents(obj), all_celltypes)
sce$body_layer <- do.call(
  dplyr::recode, c(list(.x = sce$cluster_id), as.list(all_body_layers)))
sce$tissue <- do.call(
  dplyr::recode, c(list(.x = sce$cluster_id), as.list(all_tissues)))
```

## Figure 7 Chloroplast-bearing cells

### DA Measure

```{r}
sce_chl_all <- readRDS(Sys.glob(
  "../results/ObjectCache/TrajectoryInference/sce_all_slingshot_chl_all_*.rds"))
```

```{r}
da_chl_all <- rhapsodykit::findDiffAbundantCells(
  subset(obj, cells = colnames(sce_chl_all)),
  stim = paste(1:3, "DPI-PNR2", sep = ""),
  ctrl = paste(1:3, "DPI-TR4", sep = ""),
  reduction = "harmony", npc = 30,
  k.vector = seq(50, 1000, 50)
)
```

```{r fig.height=7, fig.width=8.9}
p1 <- local({
  df_to_plot <- reducedDim(sce_chl_all, "PHATE") |>
    as.data.frame() |>
    tibble::rownames_to_column("cell")

  da_df <- data.frame(
    cell = rownames(da_chl_all$embeddings$pca),
    score = da_chl_all$cells$da.pred)

  df_to_plot <- dplyr::left_join(df_to_plot, da_df) |>
    dplyr::arrange(!is.na(score), abs(score))

  p <-  ggplot2::ggplot(df_to_plot) +
    ggplot2::geom_point(
      mapping = ggplot2::aes(x = PHATE1, y = PHATE2, col = score),
      size = 0.5) +
    ggplot2::scale_color_gradientn(colours = c("blue", "white", "red"))

  p <- ggrastr::rasterise(p)

  p <- p +
      ggplot2::coord_fixed() +
      ggplot2::labs(x = "PHATE_1", y = "PHATE_2") +
      ggplot2::guides(color = ggplot2::guide_colorbar(
        title = "DA Score", title.position = "top")) +
      cowplot::theme_cowplot(font_size = 22, font_family = "Arial") +
      theme_dimred(linesize = 1.5 * PT) +
      ggplot2::theme(
        axis.title = ggplot2::element_text(size = 22),
        plot.title = ggplot2::element_text(size = 22, face = "plain", hjust = 0.5),
        legend.title = ggplot2::element_text(size = 20),
        legend.text = ggplot2::element_text(size = 18),
        legend.key.width = grid::unit(1.2, "cm"),
        legend.key.height = grid::unit(0.7, "cm"),
        legend.direction = "horizontal",
        legend.title.align = 0.5,
        legend.position = c(0.5, 0.1))

  p
})

p1
```

```{r eval=FALSE, include=FALSE}
plotpowerpoint(p1, "../data/Figure.pptx",
  location = grid::unit(c(2.5, 4.49, 19.89, 15.63), "cm"),
  fonts = list(sans = "Arial", serif = "Arial", mono = "Courier"))
```

### Trajectories

```{r fig.height=7, fig.width=12.9}
p2 <- local({
  lapply(1:2, function(i) {
    plotLineageCurveOnReduc(
        sce_chl_all, i, dimred = "PHATE",
        linewidth = 1, point_size = 0.5,
        rasterise = TRUE, point_alpha = 1) +
      ggplot2::scale_color_viridis_c(labels = scales::number_format(accuracy = 0.1)) +
      ggplot2::coord_fixed() +
      ggplot2::labs(x = "PHATE_1", y = "PHATE_2") +
      ggplot2::ggtitle(paste("Branch", i)) +
      ggplot2::guides(color = ggplot2::guide_colorbar(
        title = "Pseudotime", title.position = "top")) +
      cowplot::theme_cowplot(font_size = 22, font_family = "Arial") +
      theme_dimred(linesize = 1.5 * PT) +
      ggplot2::theme(
        axis.title = ggplot2::element_text(size = 22),
        plot.title = ggplot2::element_text(size = 22, hjust = 0.5, face = "plain"),
        legend.key.width = grid::unit(1.2, "cm"),
        legend.key.height = grid::unit(0.7, "cm"),
        legend.text = ggplot2::element_text(size = 18),
        legend.title = ggplot2::element_text(size = 20),
        legend.direction = "horizontal",
        legend.title.align = 0.5,
        legend.position = c(0.5, 0.1))
  })
})

patchwork::wrap_plots(p2)
```

```{r fig.height=6, fig.width=22}
(p12 <- p1 + p2)
```

```{r}
plotpowerpoint(p12, "../data/Figure.pptx",
  location = grid::unit(c(2.5, 4.49, 49.01, 13.5), "cm"),
  fonts = list(sans = "Arial", serif = "Arial", mono = "Courier"))
```

### Gene Dynamic Expression

```{r}
tradeSce_chl_all <- readRDS(Sys.glob(
  "../results/ObjectCache/TrajectoryInference/tradeseq_gam_chl_all_*.rds"))

patternRes_chl_all <- readRDS(Sys.glob(
  "../results/ObjectCache/TrajectoryInference/tradeseq_patternRes_chl_all_*.rds"))
```

```{r}
yhatkm <- local({
  patternRes_df <- patternRes_chl_all |>
    tibble::rownames_to_column("gene") |>
    dplyr::mutate(fdr = p.adjust(pvalue, "fdr"))

  patternGenes <- patternRes_df |>
    dplyr::filter(fdr <= 0.01) |>
    dplyr::pull(gene) |>
    unique()

  yhatSmooth <- tradeSeq::predictSmooth(tradeSce_chl_all, gene = patternGenes, nPoints = 100, tidy = FALSE)
  yhatSmoothScaled <- t(scale(t(yhatSmooth)))

  set.seed(1124)
  fit_km <- kmeans(yhatSmoothScaled, 4, nstart = 25)

  avgtime <- split(
    x = as.data.frame(t(fit_km$centers)),
    f = stringr::str_match(
      colnames(fit_km$centers), "(lineage\\d)_")[, 2]) |>
  vapply(
    FUN.VALUE = numeric(nrow(fit_km$centers)),
    FUN = function(df) apply(df, 2, which.max)) |>
  base::rowMeans()

  row_split <- factor(
    x = paste0("G", fit_km$cluster),
    levels = paste0("G", names(sort(avgtime))))
  
  list(
    mtx = yhatSmoothScaled,
    km = fit_km,
    cluster = row_split
  )
})
```

```{r}
p3fun <- local({
  row_split <- yhatkm$cluster
  mtx <- yhatkm$mtx
  palette <- colorRamps::matlab.like

  # Calculate color bar
  mtx_uni <- unique(mtx)
  if (length(mtx_uni) < 100)
    q <- max(abs(mtx))
  else
    q <- stats::quantile(abs(mtx), probs = .99)

  bks <- seq(-q, q, length.out = 9)
  col_fun <- circlize::colorRamp2(
    breaks = bks,
    colors = palette(length(bks))
  )

  # Reverse first half of pseudotime expression matrix
  n_cols <- ncol(mtx)
  half_n_cols <- n_cols / 2
  new_order <- c(seq(half_n_cols, 1), seq(half_n_cols + 1, n_cols))
  mtx <- mtx[, new_order]

  ph_res <- ComplexHeatmap::Heatmap(
    mtx,

    use_raster = TRUE,

    # Keep original row/col order
    column_order = colnames(mtx),
    col = col_fun,

    cluster_rows = TRUE,
    show_row_names = FALSE,
    row_split = row_split,
    row_title_rot = 0,
    show_row_dend = FALSE,
    cluster_row_slices = FALSE,
    row_title_gp = grid::gpar(fontsize = 20, fontfamily = "Arial"),

    cluster_columns = FALSE,
    show_column_names = FALSE,
    show_column_dend = FALSE,
    column_split = stringr::str_match(
      colnames(mtx), "(lineage\\d)_")[, 2],
    column_title = paste("Branch", 1:2),
    column_title_gp = grid::gpar(fontsize = 20, fontfamily = "Arial"),

    heatmap_legend_param = list(
      title = "Gene Expression",
      legend_direction = "horizontal",
      legend_width = grid::unit(7, "cm"),
      title_position = "topcenter",
      title_gp = grid::gpar(fontsize = 20,fontfamily = "Arial"),
      labels_gp = grid::gpar(fontsize = 16, fontfamily = "Arial")
    )
  )

  function(...) {
    suppressWarnings(
      ComplexHeatmap::draw(
        ph_res, heatmap_legend_side = "bottom",
        align_heatmap_legend = "heatmap_left",
        legend_gap = grid::unit(1.5, "cm"),
        ...)
    )
  }
})

p3 <- p3fun()
```

```{r eval=FALSE, include=FALSE}
plotpowerpoint(p3, "../data/Figure.pptx", fun = p3fun,
  location = grid::unit(c(2.5, 18.32, 15, 15.63), "cm"),
  fonts = list(sans = "Arial", serif = "Arial", mono = "Courier"))
```

### Enrichment of Gene Cluster

```{r}
p4data <- local({
  gene_list <- split(names(yhatkm$km$cluster), paste0("G", yhatkm$km$cluster))
  gene_list <- gene_list[levels(yhatkm$cluster)]

  clusterProfiler::compareCluster(
      gene_list,
      fun = "enrichGO",
      OrgDb = "org.Taestivum.iwgsc.db",
      keyType = "GID",
      ont = "BP",
      universe = rownames(tradeSce_chl_all)) |>
    clusterProfiler::simplify(cutoff = 0.8) |>
    enrichRepresent()
})
```

```{r fig.height=7, fig.width=8}
(p4 <- p4data |>
  enrichplot::dotplot(
    showCategory = 8,
    by = "count", label_format = 50) +
   ggplot2::ggtitle("Top GO biological process") +
   ggplot2::xlab("Gene Cluster") +
   ggplot2::theme(plot.title = ggplot2::element_text(size = 20, hjust = 0.3),
                  plot.title.position = "plot",
                  axis.title = ggplot2::element_text(size = 20),
                  axis.text.x = ggplot2::element_text(size = 16),
                  axis.text.y = ggplot2::element_text(size = 16),
                  legend.title = ggplot2::element_text(size = 18),
                  legend.text = ggplot2::element_text(size = 16),
                  legend.background = ggplot2::element_blank(),
                  #legend.position = c(0.18, 0.25),
                  axis.ticks = ggplot2::element_line(linewidth = 1.5 * PT),
                  panel.border = ggplot2::element_rect(linewidth = 1.5 * PT))
)
```

```{r eval=FALSE, include=FALSE}
plotpowerpoint(p4, "../data/Figure.pptx",
  location = grid::unit(c(17.65, 18.32, 22.83, 15.63), "cm"),
  fonts = list(sans = "Arial", serif = "Arial", mono = "Courier"))
```


### Selected Gene Dynamics

```{r fig.height=13, fig.width=7}
p5 <- local({
  genedf <- data.frame(
    cluster = yhatkm$cluster,
    gene = names(yhatkm$km$cluster)
  )

  exprdf <- yhatkm$mtx |>
    as.data.frame() |>
    tibble::rownames_to_column("gene") |>
    tidyr::pivot_longer(cols = !gene,
                        names_pattern = "lineage(\\d+)_(\\d+)",
                        names_to = c("lineage", "pseudotime"),
                        values_to = "expression") |>
    dplyr::mutate(pseudotime = as.numeric(pseudotime),
                  lineage = paste("Branch", lineage))

  df_to_plot <- dplyr::left_join(exprdf, genedf, by = "gene") |>
    dplyr::select(gene, cluster, dplyr::everything()) |>
    dplyr::mutate(group = paste(gene, lineage))

  df_to_plot |>
    dplyr::filter(gene %in% c("TraesCS5A02G257700", "TraesCS2B02G549600",
                              "TraesCS2D02G200700", "TraesCS5B02G039000")) |>
    ggplot2::ggplot(ggplot2::aes(
      x = pseudotime, y = expression)) +
    ggplot2::geom_line(
      mapping = ggplot2::aes(
        group = group, color = lineage),
      linewidth = 1.5) +
    ggplot2::scale_color_brewer(type = "qual", palette = "Dark2") +
    ggplot2::scale_y_continuous(breaks = scales::breaks_extended(n = 4)) +
    ggplot2::facet_wrap(~ gene, ncol = 1, scales = "free_y") +
    ggplot2::labs(x = "Pseudotime", y = "Normalized Expression", color = "Branch") +
    ggplot2::theme_bw(base_size = 22) +
    ggplot2::theme(
      panel.grid = ggplot2::element_blank(),
      strip.text = ggplot2::element_text(
        size = 16, vjust = 0.2, margin = ggplot2::margin(t = 4, b = 4)),
      axis.text.x = ggplot2::element_text(
        size = 16, angle = 0, hjust = 0.5, vjust = 0.5, color = "black"),
      axis.text.y = ggplot2::element_text(size = 16, color = "black"),
      axis.ticks = ggplot2::element_line(linewidth = 1.5 * PT),
      strip.background = ggplot2::element_rect(linewidth = 1.5 * PT),
      panel.border = ggplot2::element_rect(linewidth = 1.5 * PT),
      legend.position = c(0.25, 0.13),
      legend.background = ggplot2::element_blank(),
      legend.title = ggplot2::element_blank())
})

p5
```

```{r}
plotpowerpoint(p5, "../data/Figure.pptx",
  location = grid::unit(c(40.75, 18.32, 10.75, 15.63), "cm"),
  fonts = list(sans = "Arial", serif = "Arial", mono = "Courier"))
```

### ISH Gene Expression

```{r}
p6 <- local({
  scater::plotReducedDim(
      sce_chl_all, "PHATE",
      colour_by = "TraesCS5B02G039000",
      order_by = "TraesCS5B02G039000",
      point_alpha = 1, point_size = 0.5,
      rasterise = TRUE) +
    ggplot2::scale_color_gradient(low = "grey", high = "blue") +
    ggplot2::coord_fixed() +
    ggplot2::ggtitle("TraesCS5B02G039000") +
    ggplot2::labs(x = "PHATE_1", y = "PHATE_2") +
    ggplot2::guides(color = ggplot2::guide_colorbar(
      title = "Expression Level", title.position = "top")) +
    cowplot::theme_cowplot(font_size = 22, font_family = "Arial") +
    theme_dimred(linesize = 1.5 * PT) +
    ggplot2::theme(
      axis.title = ggplot2::element_text(size = 22),
      plot.title = ggplot2::element_text(size = 22, face = "plain", hjust = 0.5),
      legend.title = ggplot2::element_text(size = 20),
      legend.text = ggplot2::element_text(size = 18),
      legend.key.width = grid::unit(1.2, "cm"),
      legend.key.height = grid::unit(0.7, "cm"),
      legend.direction = "horizontal",
      legend.title.align = 0.5,
      legend.position = c(0.5, 0.1))
})

p6
```

```{r}
plotpowerpoint(p6, "../data/Figure.pptx",
  location = grid::unit(c(2.5, 34.6, 15.05, 15.63), "cm"),
  fonts = list(sans = "Arial", serif = "Arial", mono = "Courier"))
```
