---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

- Quality Control
  - [Quality Control of Cells and Genes](quality_control_of_cells_and_genes.html)
  - [Find and Remove Doublets](quality_control_of_doublets.html)
  - [Ambient Gene Expressions Correction](quality_control_of_ambient_rna.html)
- Integration
  - [Testing of several data integration methods](integration_testing_report.html)
  - [Integration and Annotation of MOCK Samples by Harmony](integration_by_harmony.html)
  - [Evaluating Cluster Stability of MOCK Samples](eval_cluster_stability_mock.html)
  - [Integration and Annotation of All Samples](integration_of_all_samples.html)
  - [Sample Correlation Analysis](sample_correlation_analysis.html)
- Cell Type Annotation
  - [Developmental Process of MOCK Samples](developmental_process_of_mock_samples.html)
  - [Mesophyll and Vascular Bundle Lineages](mesophyll_vascular_lineages.html)
  - [Gene Expression Analysis of Cell Populations in Integrated Samples](analysis_of_all_samples.html)
- Differential Abundance Analysis
  - [Compositional Analysis by scDC](compositional_analysis_by_scDC.html)
  - [Compositional Analysis by scCODA](compositional_analysis_by_scCODA.html)
  - [Identify Differentially Abundant Subpopulation](differential_abundance_subpopulation.html)
  - [Co-varying Neighborhood Analysis](covarying_neighborhood_analysis.html)
- Differential State Analysis
  - [Perform Differential State Analysis](differential_state_analysis.html)
  - [Analysis of Intersecting DEG Sets](diff_state_deg_intersect.html)
  - [Known Pathways in DEGs of Each Cell Types](diff_state_known_pathways.html)
  - [Geneset Enrichment for DEGs of Differential States](diff_state_geneset_analysis.html)
  - [Find Identity DEGs from MOCK Samples](diff_state_identity_genes.html)
  - [Transcription Factor Regulation Network of DEGs](diff_state_tf_network.html)
- Trajectory Inference
  - [RNA Velocity Estimation of All Samples](rna_velocity_estimation.html)
  - [Identify the source of stress subpopulation](sources_of_stress_state_subpopulations.html)
  - [Differential Expression along Pseudotime](differential_expression_along_pseudotime.html)
- Slides for Presentation
  - [Slides for Midterm Report](slides_for_midterm_report.html)
  - [Slides for 2023 SSPP](slides_for_2023sspp.html)
  - [Slides for PhD Defense](slides_for_phd_defense.html)
- Figures for Journal Articles
  - [Figure 2: Experiment Layout](figure_2_experiment_layout.html)
  - [Figure 3: Cell Annotation](figure_3_cell_annotation.html)
  - [Figure 4: Immunity Partition](figure_4_immunity_partition.html)
  - [Figure 5: Specific Pathways](figure_5_specific_pathways.html)
  - [Figure 6: Pathogen-responsive cells](figure_6_pathogen_responsive_cells.html)
  - [Figure 7: Chloroplast-bearing cells](figure_7_chloroplast_bearing_cells.html)
