---
title: "Integration of MOCK Samples"
author: "Altair Wei"
date: "2022/5/3"
output: html_document
---

```{r setup, include=FALSE}
library(magrittr)
knitr::opts_chunk$set(echo = TRUE, autodep = TRUE)
source("../scripts/UtilityFunctions.R")
```

# MOCK 样本的整合与注释

## 1 加载数据

```{r}
samples <- c(
  "0DPI-MOCK-1",
  "0DPI-MOCK-2",

  "1DPI-MOCK-1",
  "1DPI-MOCK-2",
  "1DPI-PNR2-1",
  "1DPI-PNR2-2",
  "1DPI-TR4-1",
  "1DPI-TR4-2",

  "2DPI-MOCK-1",
  "2DPI-MOCK-2",
  "2DPI-PNR2-1",
  "2DPI-PNR2-2",
  "2DPI-TR4-1",
  "2DPI-TR4-2",

  "3DPI-MOCK-1",
  "3DPI-MOCK-2",
  "3DPI-PNR2-1",
  "3DPI-PNR2-2",
  "3DPI-PNR2-3",
  "3DPI-TR4-1",
  "3DPI-TR4-2"
)

names(samples) <- samples
```


```{r}
obj_list <- lapply(samples, function(sample) readRDS(
  Sys.glob(paste0(
    "../results/ObjectCache/QualityControl/",
    "obj_strained_", sample, "_*.rds"))
  )
)

obj_mock <- obj_list[stringr::str_which(samples, "MOCK")]
```

## 2 数据整合

我们选择 Seurat RPCA 方法来整合样本，因为 0~3DPI 的 MOCK 反应着胚芽鞘的生长发育，样本细胞之间不需要太 “对齐” 。参数 `k.anchor=5` 也选择默认值。

```{r message=FALSE, warning=FALSE}
obj_mock_combined <- xfun::cache_rds(
  file = "obj_mock_combined.rds",
  dir = "../results/ObjectCache/IntegrationAndAnnotation/",
  expr = rhapsodykit::integrated_sample_analysis(
    obj_mock, reduction = "rpca",
    k.anchor = 5, n_dims = 30,
    normalization = "LogNormalize",
    analyze = TRUE
  )
)
```

## 3 细胞类型划分

### 3.1 分辨率调整

```{r}
library(clustree)

obj_mock_combined <- xfun::cache_rds(
  file = "obj_clustree.rds",
  dir = "../results/ObjectCache/IntegrationAndAnnotation/",
  expr = local({
    obj_mock_combined <- Seurat::FindClusters(
      obj_mock_combined, resolution = seq(0, 1.6, 0.2), verbose = FALSE)
    obj_mock_combined <- choose_indent_res(obj_mock_combined, "integrated_snn_res.0.5")
    obj_mock_combined
  })
)
```

```{r fig.height=14, fig.width=10, cache=TRUE}
clustree::clustree(obj_mock_combined, prefix = "integrated_snn_res.")
```


### 3.2 降维图 {.tabset}

```{r}
ident_cols <- Seurat::DiscretePalette(length(levels(Seurat::Idents(obj_mock_combined))), palette = NULL)
```

#### t-SNE

```{r fig.height=4, fig.width=10}
p1 <- Seurat::DimPlot(obj_mock_combined, reduction = "tsne", group.by = "sample")
p2 <- Seurat::DimPlot(obj_mock_combined, reduction = "tsne", label = TRUE, repel = TRUE, cols = ident_cols)
p1 + p2 & ggplot2::coord_fixed()
```

#### UMAP

```{r fig.height=4, fig.width=10}
p1 <- Seurat::DimPlot(obj_mock_combined, reduction = "umap", group.by = "sample")
p2 <- Seurat::DimPlot(obj_mock_combined, reduction = "umap", label = TRUE, repel = TRUE, cols = ident_cols)
p1 + p2 & ggplot2::coord_fixed()
```

## 4 标志基因矩阵

```{r fig.width=15, fig.height=7}
Seurat::DefaultAssay(obj_mock_combined) <- "RNA"
plot_markers(obj_mock_combined, cluster.idents = TRUE)
```

## 5 细胞种群的标志基因

```{r cache=TRUE}
marker_cosg <- COSG::cosg(
 obj_mock_combined,
 groups = 'all',
 assay = 'RNA',
 slot = 'data',
 mu = 1,
 n_genes_user = 300
)
```

```{r cache=TRUE}
markers_df <- Seurat::FindAllMarkers(
    obj_mock_combined, only.pos = TRUE, min.pct = 0.25,
    logfc.threshold = 0.25, verbose = FALSE)
```

### 5.1 散点投影 {.tabset}

```{r fig.height=7, fig.width=11, results='asis'}
for (i in names(marker_cosg$names)) {
  cat("####", i, "\n\n")
  p <- Seurat::FeaturePlot(
      obj_mock_combined,
      features = marker_cosg$names[[i]][1:6],
      order = TRUE,
      ncol = 3) &
    ggplot2::coord_fixed()
  print(p)
  cat("\n\n")
}
```

### 5.2 气泡图 {.tabset}

```{r}
m1 <- unlist(lapply(marker_cosg$names, function(m) m[1:3]), use.names = FALSE)
m2 <- split(markers_df$gene, markers_df$cluster) %>%
  lapply(function(x) x[1:3]) %>% unlist() %>% unique()
```

#### COSG

```{r fig.width=15, fig.height=7}
Seurat::DotPlot(obj_mock_combined, assay = "RNA", features = m1, cluster.idents = FALSE) +
  ggplot2::scale_y_discrete(limits = rev) +
  ggplot2::theme(
    axis.text.x = ggplot2::element_text(angle = 90, vjust = 0.5, hjust = 1)
  )
```

#### Seurat

```{r fig.width=15, fig.height=7}
Seurat::DotPlot(obj_mock_combined, assay = "RNA", features = m2, cluster.idents = FALSE) +
  ggplot2::scale_y_discrete(limits = rev) +
  ggplot2::theme(
    axis.text.x = ggplot2::element_text(angle = 90, vjust = 0.5, hjust = 1)
  )
```

## 6 激光显微切割反卷积

### 6.1 加载 LCM 数据

```{r}
lcm_counts <- readr::read_tsv("../results/LCMSeq/gene_quanti/counts/all.featureCounts", comment = "#")
lcm_counts <- lcm_counts[!(names(lcm_counts) %in% c("Chr", "Start", "End", "Strand", "Length"))]
names(lcm_counts) <- c("Gene", basename(dirname(names(lcm_counts)[-1])))
lcm_mtx <- as.matrix(lcm_counts[-1])
rownames(lcm_mtx) <- lcm_counts$Gene
lcm_mtx <- lcm_mtx[ rowSums(lcm_mtx) > 1, ]
```

是否需要使用归一化后的表达之呢？不需要，MuSiC 就是 raw counts

```{r}
sc_counts <- SeuratObject::GetAssayData(obj_mock_combined, assay = "RNA", slot = "counts")
```

```{r}
markergenes <- unique(unlist(marker_cosg$names))
```

```{r}
#markergenes <- unique(markers_df$gene)
```

```{r}
sc_mtx <- vapply(
  X = levels(Seurat::Idents(obj_mock_combined)),
  FUN = function(i) {
    Matrix::rowMeans(
      sc_counts[markergenes, Seurat::WhichCells(obj_mock_combined, ident = i)])
  },
  FUN.VALUE = numeric(length = length(markergenes))
)

sc_mtx <- sc_mtx[ rowSums(sc_mtx) > 1, ]
```

### 6.2 运行反卷积算法

```{r}
LCM_design <- c(
  "VC_1" = "vascular",
  "VC_2" = "vascular",
  "VC_3" = "vascular",
  "CC_1" = "cortex",
  "CC_2" = "cortex",
  "CC_3" = "cortex",
  "MC_1" = "mesophyll",
  "MC_2" = "mesophyll",
  "MC_3" = "mesophyll"
)

CIBER <- RNAMagnet::runCIBERSORT(
  exprs = lcm_mtx,
  base = sc_mtx,
  design = LCM_design,
  markergenes = intersect(rownames(lcm_mtx), rownames(sc_mtx)),
  mc.cores = 3
)
```

### 6.3 可视化细胞种群比例

```{r fig.height=6, fig.width=8, dev='svglite'}
ggplot2::ggplot(
    data = CIBER,
    mapping = ggplot2::aes(
      x = factor(SampleClass, unique(LCM_design)),
      y= Fraction, color = as.character(CellType))
  ) +
  ggplot2::geom_point(stat = "summary", fun = mean) +
  ggplot2::geom_errorbar(
    stat="summary",
    fun.min = function(x) mean(x)+sd(x)/sqrt(length(x)),
    fun.max = function(x) mean(x)-sd(x)/sqrt(length(x)),
    width = 0.2
  ) +
  ggplot2::scale_y_continuous(labels = scales::percent) +
  ggplot2::facet_wrap(~ CellType, scales = "free_y") +
  ggplot2::theme_bw(base_size=12) +
  ggplot2::theme(
    axis.text.x = ggplot2::element_text(angle = 90),
    panel.grid = ggplot2::element_blank()
  ) +
  ggplot2::guides(color = "none") +
  ggplot2::ylab("CIBERSORT estimate (a.u.)") +
  ggplot2::xlab("Niche")
```

```{r}
mtx_df <- CIBER %>%
  dplyr::group_by(SampleClass, CellType) %>%
  dplyr::summarise(
    MeanFrac = mean(Fraction)
  ) %>%
  dplyr::select(CellType, SampleClass, MeanFrac) %>%
  tidyr::pivot_wider(names_from = SampleClass, values_from = MeanFrac)

mtx <- as.matrix(mtx_df[, -1])
rownames(mtx) <- mtx_df$CellType
```

```{r fig.height=5, fig.width=4}
ComplexHeatmap::Heatmap(
  matrix = mtx,
  col = c("white", "blue", "red"),
  row_dend_width = grid::unit(4, "cm"),
  column_order = unique(LCM_design),
  heatmap_legend_param = list(
    title = "Fraction",
    #title_position = "leftcenter",
    legend_direction = "vertical",
    legend_height = grid::unit(4, "cm")
  )
)
```


## 7 细胞类型注释

### 注释

```{r}
obj_mock_annotated <- xfun::cache_rds(
  file = "obj_mock_annotated.rds",
  dir = "../results/ObjectCache/IntegrationAndAnnotation/",
  expr = local({
    Seurat::DefaultAssay(obj_mock_combined) <- "integrated"
    obj_mock_combined <- Seurat::RenameIdents(
      obj_mock_combined,

      # Vascular Cells
      `11` = "Va_1",
      `7`  = "Va_2",
      `8`  = "Va_3",
      `2`  = "Va_4",
    
      # Cortex Cells
      `3`  = "Co_1",
      `4`  = "Co_2",
      `6`  = "Co_3",
    
      # Mesophyll Cells
      `10` = "Me_1",
      `1`  = "Me_2",
      `15` = "Me_3",
      `9`  = "Me_4",
      `0`  = "Me_5",
      `14` = "Me_6",

      # Epidermal Cells
      `12` = "Ep_1",
      `13` = "Ep_2",
      `17` = "Ep_3",
    
      # Guardian Cells
      `16` = "Gu",
    
      # Unknown Cells
      `5`  = "Un_1"
    )

    obj_mock_combined
  })
)
```

### 降维图 {.tabset}

#### t-SNE

```{r}
Seurat::DimPlot(
    obj_mock_annotated,
    reduction = "tsne",
    label = TRUE,
    repel = TRUE,
    cols = ident_cols) +
  ggplot2::coord_fixed()
```

#### UMAP

```{r}
Seurat::DimPlot(
    obj_mock_annotated,
    reduction = "umap",
    label = TRUE,
    repel = TRUE,
    cols = ident_cols) +
  ggplot2::coord_fixed()
```

## 8 细胞类型比例

```{r}
rhapsodykit::barplot_cluster_abundance(obj_mock_annotated) +
  ggplot2::scale_fill_discrete(type = ident_cols)
```

```{r fig.height=7, fig.width=14}
rhapsodykit::barplot_cluster_abundance(obj_mock_annotated, position = "dodge") +
  ggplot2::theme(
    strip.text.x = ggplot2::element_text(size = 16)
  )
```

## 9 特征基因的功能法分析

```{r message=FALSE, warning=FALSE, results="hide"}
library(org.Taestivum.iwgsc.db)
orgdb <- org.Taestivum.iwgsc.db
background <- rownames(Seurat::GetAssayData(obj_mock_annotated, assay = "RNA", slot = "count"))
```

```{r}
markerlist <- COSG::cosg(
 obj_mock_annotated,
 groups = 'all',
 assay = 'RNA',
 slot = 'data',
 mu = 1,
 n_genes_user = 100
)

markerlist <- markerlist$names
```


```{r}
performMarkerCompareORA <- function(
  markerlist, clusters, background,
  ont = c("BP", "MF", "CC", "ALL"),
  simplify = TRUE
) {
  ont <- match.arg(ont)

  if (is.null(names(clusters)))
    names(clusters) <- clusters

  compare_df <- purrr::imap(clusters, function(clr, clr_name) {
    df <- data.frame(
      gene = markerlist[[clr]],
      cluster = rep(clr_name, length(markerlist[[clr]]))
    )
    df
  }) %>%
    dplyr::bind_rows()

  compare_df$cluster <- factor(compare_df$cluster, levels = names(clusters))
  
  comp_enr <- clusterProfiler::compareCluster(
    gene ~ cluster,
    data = compare_df,
    fun = "enrichGO",
    OrgDb = org.Taestivum.iwgsc.db,
    keyType = "GID",
    ont = ont,
    universe = background
  )

  if (simplify && ont != "ALL")
    comp_enr <- clusterProfiler::simplify(comp_enr, cutoff = 0.5)
  
  comp_enr
}
```

### 维管束与皮层细胞

```{r}
enr <- performMarkerCompareORA(
  markerlist,
  paste0("Va_", 1:4),
  background
)
```

```{r fig.height=8, fig.width=12, message=FALSE, warning=FALSE}
p <- enr %>%
  enrichplot::pairwise_termsim() %>%
  enrichplot::treeplot(
    showCategory = 40, nCluster = 12,
    offset = 1, offset_tiplab = 1.8,
    label_format_cladelab = 5,
    geneClusterPanel = "dotplot", cex_category = 6, nWords = 0) +
  ggplot2::scale_y_continuous(expand = ggplot2::expansion(mult = 0, add = 2)) +
  ggplot2::coord_cartesian()
p
```

### 皮层细胞

```{r}
enr <- performMarkerCompareORA(
  markerlist,
  paste0("Co_", 1:3),
  background
)
```

```{r fig.height=8, fig.width=8, message=FALSE, warning=FALSE}
p <- enr %>%
  enrichplot::pairwise_termsim() %>%
  enrichplot::treeplot(
    showCategory = 40, nCluster = 12,
    offset = 1.2, offset_tiplab = 2.4,
    label_format_cladelab = 5,
    geneClusterPanel = "dotplot", cex_category = 6, nWords = 0) +
  ggplot2::scale_y_continuous(expand = ggplot2::expansion(mult = 0, add = 2)) +
  ggplot2::coord_cartesian()
p
```

### 叶肉细胞

```{r}
enr <- performMarkerCompareORA(
  markerlist,
  paste0("Me_", 1:6),
  background
)
```

```{r fig.height=9, fig.width=12, message=FALSE, warning=FALSE}
p <- enr %>%
  enrichplot::pairwise_termsim() %>%
  enrichplot::treeplot(
    showCategory = 40, nCluster = 12,
    offset = 1, offset_tiplab = 1.2,
    label_format_cladelab = 5,
    geneClusterPanel = "dotplot", cex_category = 6, nWords = 0) +
  ggplot2::scale_y_continuous(expand = ggplot2::expansion(mult = 0, add = 2)) +
  ggplot2::coord_cartesian()
p
```

### 其他细胞

```{r}
enr <- performMarkerCompareORA(
  markerlist,
  c("Ep_1", "Ep_2", "Ep_3", "Gu", "Un_1"),
  background
)
```

```{r fig.height=9, fig.width=12, message=FALSE, warning=FALSE}
p <- enr %>%
  enrichplot::pairwise_termsim() %>%
  enrichplot::treeplot(
    showCategory = 40, nCluster = 12,
    offset = 1, offset_tiplab = 1.4,
    label_format_cladelab = 5,
    geneClusterPanel = "dotplot", cex_category = 6, nWords = 0) +
  ggplot2::scale_y_continuous(expand = ggplot2::expansion(mult = 0, add = 2)) +
  ggplot2::coord_cartesian()
p
```



